### ISSUE TITLE
setPlayRate is not working

### ISSUE THREAD

**Issue by rahul-peerbits** [muhku/FreeStreamer#101]
Hello,

I am trying to change rate of audio while streaming. I already increased maxPrebufferedByteCount but it still not works. I also tried to set rate 0.5 but still no change in playback rate.

Could you help me to figure out what i miss here?

Thanks in advance

**Comment by inorganik** [comment]
I'm not able to get setPlayRate working either, even while playing. With a breakpoint on the function, the last line `AudioQueueSetParameter(m_outAQ, kAudioQueueParam_PlayRate, playRate);` fires. Not sure why it doesn't seem to have any effect. Tried it on .mp3 and .m4a.

**Comment by juanjoguevara** [comment]
inorganik is right setPlayRate dont work

**Comment by YoungLion** [comment]
setPlayRate is not working for me even if I set it when audio is playing. I even increased the bufferSize to 10x of default configuration. Please help. Thanks in advance.
