### ISSUE TITLE
Strange crashes

### ISSUE THREAD

**Issue by skopanev** [muhku/FreeStreamer#126]
Hi Mat! Hope you doing well.

Sometime I have strange crashes. I'm not sure but it happens by following next steps:
1/ Open app
2/ Run stream
3/ Stop stream (while buffering or just started)
4/ Close app

Seems like app tried to close opening queue or something like this.

Here is smth from my crashlogs:
astreamer::Audio_Queue::~Audio_Queue() (audio_queue.cpp:74)
astreamer::Audio_Queue::~Audio_Queue() (audio_queue.cpp:68)
astreamer::Audio_Stream::close(bool) (audio_stream.cpp:255)
[FSAudioStreamPrivate stop] (FSAudioStream.mm:747)
[FSAudioStreamPrivate interruptionOccurred:] (FSAudioStream.mm:620)

Thanks,

**Comment by skopanev** [comment]
Seems like fixed in new version.

**Comment by skopanev** [comment]
HI @muhku! Hope you well!

I've found how to reproduce this crashes. Reproducible about 96%.
Unfortunatelly I can't find Airplay support in your app (that I can not reproduce it with your own example app):
1/ Run stream & play via AirPlay (AppleTV)
2/ Switch Wifi to 3G, wait for few seconds and then back to WiFi
3/ App crashes

Usually this crash:
![image]
(http://cl.ly/image/011q1a211d2w/Image%202015-02-20%20at%202.13.59%20PM.png)

Rarely something like:
![image2]
(http://cl.ly/image/033Q2A2j1f0R/Image%202015-02-20%20at%202.55.37%20PM.png)

**Comment by syrakozz** [comment]
+1

**Comment by muhku** [comment]
@skopanev: This happens with the bundled (Apple) Reachability? I think what happens is that the notification is posted on another thread than main and the streamer crashes as a result. Apple's code doesn't look very thread-safe to me. Could you try replacing Reachability.m / Reachability.h from @tonymillion Reachability (https://github.com/tonymillion/Reachability)?

**Comment by muhku** [comment]
Well, you could also pull the @tonymillion Reachability from master now. With the CocoaPod this has been already bundled for a while. Let me know if this helps.

**Comment by skopanev** [comment]
@muhku Yes, it happens with Apple's reachibility. I've tried to update it to latest version and have same errors. Will try with tonymotion one. Thanks,

**Comment by skopanev** [comment]
@muhku It is muuuuch more stable for now.

But few crashes were — one as like in my last picture and here (it was earlier, but not so often):

![image]
(http://cl.ly/image/2R1Z442S353z/Image%202015-02-21%20at%2012.19.14%20PM.png)

**Comment by muhku** [comment]
@skopanev: Good. So the Apple Reachability randomly used some other than the main thread for its notifications and that caused the first bunch of crashes. It is a bit difficult to read your stack traces as they are cut in half so cannot see what is on the top of the stack when the crash occurs.

I could almost bet that something is calling FSAudioStream from some other than the main thread. If you could please run your application with a debug build (so that assertions get compiled in) and pull commit 2ec0d8719096a631335660ec259253b861ff1270. In that way the assert will catch the call from the offending thread and you should be able to catch the call before you get the crash.

**Comment by muhku** [comment]
Changes also tagged in 2.11.3.

**Comment by skopanev** [comment]
I've rechecked — just pressed stop/play, change stations — everything works ok. When I follow my behavior then assertion appears!

I see we are on right way.
Assertion here...
![image]
(http://cl.ly/image/1i2Z350W0N1s/Image%202015-02-21%20at%204.18.36%20PM.png)

@muhku please let me know If I can give you more info related to crash. Thanks,

**Comment by skopanev** [comment]
Possible it is my fault — because I call "Stop" FreeStreamer in notification **AVAudioSessionRouteChangeNotification**.

Shall I add something like "Call from MainThread" ?

Thanks,

**Comment by muhku** [comment]
Yes. If you are calling FSAudioStream from any other thread than main, you need to call from the main thread (see https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ#is-it-safe-to-use-the-streamer-from-multiple-threads). Luckily the fix should be quite easy:

<pre>
if ([NSThread isMainThread]) {
     // We are the main thread, just directly call:
     [audioController stop];
} else {
    // We are not on the main thread, use GCD for the main thread:
    dispatch_async(dispatch_get_main_queue(), ^{
        [audioController stop];
     });
}
</pre>

**Comment by skopanev** [comment]
Hi @muhku!

I've added notification handler to main thread — seems like working ok. Will continue checking.

Close ticket. Thanks,
