### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by nicholaswyoung** [muhku/FreeStreamer#131]
I'm using this library in Swift, and I can't seem to figure out how to access ```FSAudioStream#onMetaDataAvailable```. If you happen to have any insight into how this handler might be written in Swift, I would appreciate it.

**Comment by cyberjaime45** [comment]
I'm using this library in one of my Apps, recently i decided to translate to swift, but I stopped due to lack of time.It works just fine on my device.  This is not perfect but it will give an idea.
   func metaDataAvailable(){
        self.audioController!.stream.onMetaDataAvailable = {(metaData:Dictionary!) in
            self.streamInfo =  NSMutableString()
            if (metaData["StreamTitle"]?.length > 0 ){
                
                self.streamInfo.appendString(metaData["StreamTitle"] as NSString)
                
            }else if (metaData["IcecastStationName"]?.length > 0){
                self.streamInfo.appendString(metaData["IcecastStationName"] as NSString)
            }
            self.statusLabel.hidden = false
            
            /*
            let artistSeparation:NSArray = streamInfo.componentsSeparatedByString(" _ ") as NSArray
            if artistSeparation.count > 0 {
            }
            */
            
            if (self.streamInfo.length == 0 || self.streamInfo.isEqualToString(" ")){
                self.statusLabel.text = self.mediaItems.title
                self.streamInfo = NSMutableString(string: self.mediaItems.title)
            }else{
                self.statusLabel.text = self.streamInfo
            }
        }
        infoCenter()
    }

**Comment by nicholaswyoung** [comment]
@cyberjaime45 Thanks! How are you connecting this method to the ```metaDataAvailable``` handler on ```FSAudioStream```? That's the main problem I'm having in translating the example code.

**Comment by nicholaswyoung** [comment]
@cyberjaime45 Would you be willing to share your Swift method for updating the info center?

**Comment by cyberjaime45** [comment]
Sorry, I went to bed really early. 

Well i have  metaDataAvailable() function inside viewWillAppear. 
      //FSAudioStreamState
        self.onStateChange()
        //Audio Stream Ocurred
        self.audioStreamErrorOcurred()
        //On Meta Data Available
        self.metaDataAvailable()

About the infoCenter, this is a small feature i developed for objective c, but it looks like does not work when i translated to swift. My app has a bunch of internet radios, so i wanted to add the radio logo to MPNowPlayingInfoCenter along with the metadata. 
For example:
if radio one is playing, then the album art(logo) for that specific radio  is shown. 

This method also separates the metadata into a nice format. This used to work just fine using objective C, however I think i need to come back and refactor again to make it work the way i want. 

 //MARK: - Info center
    func infoCenter(){
        var mediaTtile = " "
       var mediaImage = UIImage(named: "no_album_art.jpg")
        
        var mediaArtAlbum = MPMediaItemArtwork()
        if (self.streamInfo.isEqualToString(" ") || self.streamInfo.length == 0){
            mediaTtile = self.mediaItems.title
        }else{
         mediaTtile = self.streamInfo
        }
     
        if(self.backgroundImage.image == nil){
            mediaArtAlbum = MPMediaItemArtwork(image: mediaImage)
        }else{
            mediaArtAlbum = MPMediaItemArtwork(image: self.backgroundImage.image)
        }
        //mediaArtAlbum = MPMediaItemArtwork(image: mediaImage)
        MPNowPlayingInfoCenter.defaultCenter().nowPlayingInfo = [MPMediaItemPropertyTitle: self.mediaItems.title, MPMediaItemPropertyArtist: mediaTtile, MPMediaItemPropertyArtwork:mediaArtAlbum]
    }

As you can see, this method gets updated every time there's a change on the metadata. In the future, I will probably move this method to a manager (singleton). It will make more sense doing that!

**Comment by nicholaswyoung** [comment]
@cyberjaime45 No worries. I stopped work early too. 

My main struggle is getting the Dictionary provided to onMetaDataAvailable into a format that I can split into the various parts. I thought ```slice``` would do it, but no dice. The Dictionary items are cast as ```AnyObject```, and I can't seem to convert them into Strings. 

Coming from languages like JavaScript, Ruby, and PHP -- Swift is "fun". But that said, I'm impressed so far.

**Comment by Gurpartap** [comment]
I don't use `onMetaDataAvailable` myself, but I ended up trying it with Swift a while ago. Here's how you would implement the handler.

```Swift
private func _enableEventHandlersForStream(stream: FSAudioStream) {
    stream.onStateChange = self._streamStateChangeHandler()
    stream.onFailure = self._streamFailureHandler()
    stream.onMetaDataAvailable = self._streamMetaDataAvailableHandler()
}


private func _streamMetaDataAvailableHandler() -> ([NSObject : AnyObject]!) -> Void {
    return { metaData in
        ...
    }
}
```

To whomsoever it may be useful, I have a port (similar) of `FreeStreamerMobile`'s failure and meta data handling Objective-C code.

Check out the Gist: https://gist.github.com/Gurpartap/2822d0b0b957d5ac65de

PS: I have not tested this code.

'Hope it helps.
