### ISSUE TITLE
Small durantion files are not working

### ISSUE THREAD

**Issue by rahul-patel** [muhku/FreeStreamer#132]
Hello,

Up to 3-4 seconds mp3 files from server are not playing and showing below error.

FSAudioStream: Error opening the stream: The stream startup watchdog activated: stream didn't start to play in 30 seconds [FreeStreamer 2.9.10] URL: http://WEBURL/1420563127543.mp3
bufferCount: 16
bufferSize: 65536
maxPacketDescs: 1024
decodeQueueSize: 128
httpConnectionBufferSize: 1024
outputSampleRate: 44100.000000
outputNumChannels: 1
bounceInterval: 10
maxBounceCount: 4
startupWatchdogPeriod: 30
maxPrebufferedByteCount: 1000000
format: formatID: .mp3, sample rate: 22050.000000
userAgent: FreeStreamer/2.9.10 (iOS 8.1.2)
cacheDirectory: /var/mobile/Containers/Data/Application/7B37B9F6-8CE3-4422-9571-FE076B1D1B5F/Documents
predefinedHttpHeaderValues: (null)
cacheEnabled: YES
maxDiskCacheSize: 100000000
requiredInitialPrebufferedByteCountForContinuousStream: 100000
requiredInitialPrebufferedByteCountForNonContinuousStream: 50000

**Comment by muhku** [comment]
Buffering size limits are now ignored if over 90% of a non-continuous stream is buffered. This should fix the issue.

**Comment by sadhiappan** [comment]
@muhku I think fix should also fix #133. Right?
