### ISSUE TITLE
Some code issue

### ISSUE THREAD

**Issue by Karpot** [muhku/FreeStreamer#136]
I played around and found some small optimization with big impact. 

1. buffer copy had a bug and no double write
		/*
		 * The analyzer is free. Copy the data to the buffer to be analyzer.
		 */
		size_t buffer = sizeof(int16_t) * MIN(kSFrequencyDomainAnalyzerSampleCount, count);

		memcpy(_sampleBuffer, samples, sizeof(int16_t) * MIN(kSFrequencyDomainAnalyzerSampleCount, count));

		size_t diff = sizeof(_sampleBuffer) - buffer;

		if( diff > 0 )
		{
			memset(_sampleBuffer + ( sizeof(_sampleBuffer) - diff), 0, diff);
		}

2. idle processorMainLoop
        if (_bufferModified) {
         ...
	}
	else
	{
		/*[[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode [NSDate distantFuture]];*/
		[NSThread sleepForTimeInterval:.01];
	}

**Comment by muhku** [comment]
Thanks, very nice. Really helps with the CPU load.
