### ISSUE TITLE
Background play can't play next one sound

### ISSUE THREAD

**Issue by javalipengfei** [muhku/FreeStreamer#140]
Hi muhku:
      first thank you for the great job.I use it  in my new program.but i have a issues.when i play a sound in foreground, it can play next when sound play  finish . but when it in background,it can play sound,but it can't auto play next sound. I can't find the reason,can you fix it ,thank you very much.

**Comment by javalipengfei** [comment]
Hi, I find when i user the catch like this configer.cacheEnabled=YES,it can't play next sound.can you slove it . thanks very much

**Comment by javalipengfei** [comment]
I found the real question.when the catchData is the max size. it can't auto play next sound in background.

**Comment by muhku** [comment]
Which FreeStreamer version are you using?

**Comment by javalipengfei** [comment]
I forget it, now  I try the new one。

**Comment by javalipengfei** [comment]
@muhku  i use the new one.I found a new program. when I pause a  voice in background. some minute later, I play it in forground. it have error:Network failed: cannot play the audio stream, how did I do something wrong

**Comment by muhku** [comment]
Continuing in Issue#144
