### ISSUE TITLE
Stream stops playing the audio but still sending metadata

### ISSUE THREAD

**Issue by tolew1** [muhku/FreeStreamer#142]
There is a strange behavior that is happening. I have it in a dev app right now. It doesn't seem to reconnect if it loses connection. The weird part is the audio stops playing but the metadata(shoutcast/icecast) is still being sent because the song title changes if you don't do anything when this happens. I have to restart the whole stream for it to start playing again. It doesn't always do it and it's not easy to recreate it. It's seems random but I think it could be network related and that it doesn't handle packet loss perhaps. Not sure of the problem.

**Comment by anujsaini512** [comment]
I'm experiencing exactly the same behavior too. Stream's metadata keeps coming in, that means it is connected. But audio doesn't get played after it encounters a pause due to weak connection or any other reason.

**Comment by taruntyagi697** [comment]
@anujsaini512 you're absolutely correct. I'm facing this issue too. I just replaced an old streaming library with this. It does everything perfect. Recording is awesome. But I can't seem to find a fix or workaround for losing the audio part. It is strange inconsistency. @muhku, would you please address this ?

**Comment by muhku** [comment]
Would be very helpful to have some logs when this happens.

**Comment by tolew1** [comment]
@muhku Thanks for the response. This is what I received one of the times it happened the other day. I changed the stream URL in the error so that it wasn't public but this is the error below. When this happens it keeps going but with no audio. I have to restart the stream for it to come back. 

2015-01-16 12:56:55.336 Mystreamingapp[1340:1313485] FSAudioStream: Network error: The operation couldn’t be completed. Socket is not connected [FreeStreamer 2.9.15] URL: http://thedomain.com/stream

bufferCount: 16

bufferSize: 65536

maxPacketDescs: 1024

decodeQueueSize: 128

httpConnectionBufferSize: 1024

outputSampleRate: 44100.000000

outputNumChannels: 2

bounceInterval: 10

maxBounceCount: 4

startupWatchdogPeriod: 30

maxPrebufferedByteCount: 1000000

format: formatID: .mp3, sample rate: 44100.000000

userAgent: FreeStreamer/2.9.15 (iOS 8.1.2)

cacheDirectory: /var/mobile/Containers/Data/Application/B83F9631-CEA9-4757-9C61-3CBF32854421/Documents

predefinedHttpHeaderValues: (null)

cacheEnabled: YES

seekingFromCacheEnabled: YES

maxDiskCacheSize: 100000000

requiredInitialPrebufferedByteCountForContinuousStream: 100000

requiredInitialPrebufferedByteCountForNonContinuousStream: 50000

**Comment by muhku** [comment]
Thanks. The error seems to be the same as in Issue #117

The strange part is that there shouldn't be no more data coming from a socket which is closed.

**Comment by tolew1** [comment]
@muhku Ok I noticed that but it did seem that was when switching networks but it doesn't appear that is the only time this happens. It is strange that data still comes through because what could be happening is that it's actually recovering/reconnected but the audio does not come back. Not sure. By the way, all my test are on Wifi, and different why networks too. I haven't tested them on mobile networks as my devices are wifi only. Is that issue 117 fixed?

**Comment by muhku** [comment]
Let's move this discussion to Issue #144. Commit and possible workaround there.
