### ISSUE TITLE
Random Unsupported format error:

### ISSUE THREAD

**Issue by tolew1** [muhku/FreeStreamer#143]
@muhku I'm also running into this strange behavior. Sometimes when I start a station I get this error message and I get the station is offline message, but if I just try it again immediately, it starts playing. These are all typically mp3 streams. It happens on various stations and it's random. This is an actual error below and an actual shoutcast URL it happened on. Any ideas about this?

2015-01-19 02:18:52.787 Mystreamingap[1617:1549036] FSAudioStream: Unsupported format error: formatID: .mp2, sample rate: 32000.000000 not supported for streaming [FreeStreamer 2.9.15] URL: http://108.61.20.174:10030
bufferCount: 16
bufferSize: 65536
maxPacketDescs: 1024
decodeQueueSize: 128
httpConnectionBufferSize: 1024
outputSampleRate: 44100.000000
outputNumChannels: 1
bounceInterval: 10
maxBounceCount: 4
startupWatchdogPeriod: 30
maxPrebufferedByteCount: 1000000
format: formatID: .mp2, sample rate: 32000.000000
userAgent: FreeStreamer/2.9.15 (iOS 8.1.2)
cacheDirectory: /var/mobile/Containers/Data/Application/4D7F602A-4F51-4431-BBF8-6423EC286719/Documents
predefinedHttpHeaderValues: (null)
cacheEnabled: YES
seekingFromCacheEnabled: YES
maxDiskCacheSize: 100000000
requiredInitialPrebufferedByteCountForContinuousStream: 100000
requiredInitialPrebufferedByteCountForNonContinuousStream: 50000

**Comment by muhku** [comment]
Yeah, I have gotten the same error too sometimes with BassDrive. It seems that somehow the audio file stream parser randomly parses incorrect type for the stream and thus the audio converter gets the wrong info. I would firstly verify if this is expected behavior from the Apple API or a bug.

**Comment by jayjayesh** [comment]
i have same issue see my Log , Note:- i have changed Radio stream url [change some numbers in url]  

 Radio App[4239:554222] FSCheckContentTypeRequest: Unable to determine content-type for the URL: http://192.81.248.192:1234/, error The network connection was lost.

 Radio App[4239:554222] FSAudioController: Failed to check the format, trying to play anyway, URL: http://192.81.248.192:1234/

**Comment by muhku** [comment]
The stream will now try to auto restart itself, if it encounters an unsupported format.
