### ISSUE TITLE
 Socket is not connected

### ISSUE THREAD

**Issue by javalipengfei** [muhku/FreeStreamer#144]
@muhku  ,when I pause a sound in background  a long time,I play it again, It take the error:
2015-01-22 17:42:22.843 FreeStreamerMobile[705:111540] FSAudioStream: Network error: The operation couldn’t be completed. Socket is not connected [FreeStreamer 2.9.15] URL: http://fmcdn.duole.com/group1/cd/d5/56dd99583b32faf0a3f28f3d6ea5.mp3
bufferCount: 8
bufferSize: 32768
maxPacketDescs: 512
decodeQueueSize: 128
httpConnectionBufferSize: 1024
outputSampleRate: 44100.000000
outputNumChannels: 1
bounceInterval: 10
maxBounceCount: 4
startupWatchdogPeriod: 30
maxPrebufferedByteCount: 1000000
format: formatID: .mp3, sample rate: 44100.000000
userAgent: FreeStreamer/2.9.15 (iOS 8.1.2)
cacheDirectory: /var/mobile/Containers/Data/Application/0872DA57-9AB9-448C-A96D-C6F153BA9CFC/Documents
predefinedHttpHeaderValues: (null)
cacheEnabled: YES
seekingFromCacheEnabled: YES
maxDiskCacheSize: 100000000
requiredInitialPrebufferedByteCountForContinuousStream: 100000
requiredInitialPrebufferedByteCountForNonContinuousStream: 50000

**Comment by muhku** [comment]
I should probably add a new specific type of error for disconnected sockets. Then you could handle the situation in the app code. It seems that iOS can close the socket in many situations: low memory, backgrounding, network errors, etc.

**Comment by muhku** [comment]
Say, kFsAudioStreamErrorStreamDisconned could be added.

**Comment by javalipengfei** [comment]
@muhku  thanks for it. what's the time to add the kFsAudioStreamErrorStreamDisconned.

**Comment by muhku** [comment]
You can also just handle the network error and do the error handling there. Restarting the stream etc. I'll take a look at this a bit later.

**Comment by javalipengfei** [comment]
@muhku  thanks very much

**Comment by muhku** [comment]
Bu ke qi :)

**Comment by muhku** [comment]
Commit 66e88b0b1d8a0830fc191f806ea386b1a4a72f6b now adds an automatic restart after network failures. Does it help?

**Comment by javalipengfei** [comment]
@muhku  I use the new code,It can't slove it  profect.what the reason for the issue.it is strange about that: pause in background a little and play in foreground.it will be happen something. and there is a new issure when i seeked:SAudioStream: Network error: HTTP response code 206 [FreeStreamer 2.9.16] URL: http://fmcdn.duole.com/group1/cd/d5/56dd99583b32faf0a3f28f3d6ea5.mp3,I hope find the real reason and slove it, however, thanks ,I will try find the reason .you are doing a great job.

**Comment by muhku** [comment]
Fixed the seeking regression, commit fa463b2d6644dfdbfdbe898f9712d64ad0bf138f

This should be OK now.
