### ISSUE TITLE
Audio Streamer gets stuck at buffering

### ISSUE THREAD

**Issue by OliverDimitrov** [muhku/FreeStreamer#151]
@muhku I've encountered another problem.

I'm testing the stream with very poor internet connections. (On device -> developer -> status - > very bad network). The scenario:
Hit play, it buffers for a long period of time, which is understandable, and then (finally) it starts. It plays for a little time, 5 to 10 sec, and then it goes again in "Buffering" state. 

The thing is that it never goes out of it. I've leaved it for like 5min and nothing happened. 

Any light on this problem?

Tnx in advance,
Oliver

**Comment by muhku** [comment]
Usually in real life network conditions the connection goes bad for some time and then again recovers to a bit better level. If the network connection stays in a level where the stream cannot get enough data (the initial long buffering time suggests that) the streamer cannot function.

**Comment by OliverDimitrov** [comment]
But If the network connection is bad, it will go again in buffering state until again it has enough data to continue. This one is stuck. 

But on your suggestion about the recovering network signal, in addition to the previous scenario - while in the second buffering state, I've returned the signal strength to "device -> developer -> status - > wi-fi signal". But nothing happened. It stays in buffering state. 

I've tried setting different configuration for the streamer (bigger/smaller buffers, different bounce interval and max bounce count), but it didn't help.

You can reproduce this scenario on your example. By running your example I've noticed some error logs:
**-FSCheckContentTypeRequest: Unable to determine content-type for the URL: http://str0.creacast.com:80/ice_radio, error The request timed out.
-FSAudioController: Failed to check the format, trying to play anyway, URL: http://str0.creacast.com:80/ice_radio**

Even setting "strictContentTypeChecking" did not help.

Please can you have second look at it?

PS: On the same connection, the stream on android works, without interruption.

**Comment by muhku** [comment]
This was a regression from the seeking from the memory buffers. Fix in commit 88dc7e03c10523711b9afedc6ea78123b612edd3
