### ISSUE TITLE
Install via pods fails

### ISSUE THREAD

**Issue by grosch** [muhku/FreeStreamer#152]
I just switched to installing this via my Podfile for my iOS project using the latest Xcode.  When I build I get some C++ type errors:

```
Undefined symbols for architecture arm64:
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      void std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::__push_back_slow_path<unsigned char const&>(unsigned char const&&&) in libPods-FreeStreamer.a(http_stream.o)
      void std::__1::vector<__CFString const*, std::__1::allocator<__CFString const*> >::__push_back_slow_path<__CFString const*>(__CFString const*&&) in libPods-FreeStreamer.a(http_stream.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Note that I'm targeting iOS 6 if that matters.

**Comment by muhku** [comment]
Does this help? https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ#i-get-a-build-error-when-installed-from-cocoapods

**Comment by grosch** [comment]
C++ Standard library says:  libstdc++ (GNU C++ standard library)
C++ Language Dialect says: GNU++11 [-std=gnu++11]

It builds without issue now, but when it runs I get a EXC_BAD_ACCESS in HTTP_Stream::canHandleUrl on the CFURLCopyScheme() call.    The value of url is @"http://199.180.72.2:8025"

**Comment by muhku** [comment]
Closing. This sounds like a problem in the local dev environment instead of a FreeStreamer bug.

**Comment by grosch** [comment]
Wow, this is pretty sad.  I took a perfectly good FreeStreamer enabled app, removed the local copy of FreeStreamer and added the Pods copy.  Now it fails to run.  That doesn't sound at all like a local dev environment issue to me.
