### ISSUE TITLE
AVAudioSession - Deactivating an audio session that has running I/O

### ISSUE THREAD

**Issue by mmcdole** [muhku/FreeStreamer#153]
I'm running into an issue that seems similar to #147 but with some minor differences.  I'm running the latest FreeStreamer '2.10.2'. 

###  Issue:

When creating a new ```FSAudioStream``` with a local file directly after another one finishes, I'll get the 'AVAudioSession - Deactivating an audio session that has running I/O' error.

###  Steps to reproduce:

1.  Play a local file in a ```FSAudioStream``` instance.
2.  Let playback finish.  
3.  On the ```kFsAudioStreamPlaybackCompleted``` state change event immediately set the current stream to nil, initiate a new ```FSAudioStream``` and start playing another local file.
4.  The new ```FSAudioStream``` will play audio for 1 second then fail with the above "AVAudioSession" error.

### Work Around:

I'm currently using this workaround which seems to get around the issue:

1.  Play a local file in a FSAudioStream instance.
2.  Let playback finish.  On the ```kFsAudioStreamPlaybackCompleted``` state change event, set a flag for 'hasPlaybackEnded'.
3.  On the next ```kFsAudioStreamStopped``` event, check if the previously created flag 'hasPlaybackEnded' is true, proceed to step step 4.
4.  Immediately initiate a new ```FSAudioStream``` and start playing another local file.
5.  The new ```FSAudioStream``` will play without issue.

I suspect there is some race condition where trashing an ```FSAudioStream``` immediately when ```kFsAudioStreamPlaybackCompleted``` triggers causes some issue, but by the time the following ```kFsAudioStreamStopped``` event triggers, it is now safe to trash the player and create a new one.

This doesn't seem to happen to me when playing remote streams which again makes me think it might be a race condition that only rears it's head on local files.

**Comment by muhku** [comment]
Thanks for the report. I have never thought about the use case of multiple streams with the audio session so there certainly is a race condition. Basically we would need to split out the audio session in a separate reference counted global class (instance) which would only close the session when there are no streamer instances requiring an audio session. Anybody who could take a look into that?

**Comment by Gurpartap** [comment]
I encountered this with remote audio file which was playing from cache (with FreeStreamer v2.9.7). After updating to HEAD today, the problem seems to have vanished.

**Comment by mmcdole** [comment]
I almost wonder if the handling of the AVAudioSession should be optional.  

I personally would be fine with handling this myself outside of FreeStreamer, and outside of any one particular FSAudioStream.  When using AVPlayer, it is still my responsibility to handle the creation and activation of the AVAudioSession myself.  I consider that situation and the one with FreeStreamer pretty similar.

Perhaps leave it in on by default for users who just want background audio to "work" out of the box, but I would like to disable FreeStreamer's handling of the AVAudioSession myself so I can have more fine-grained control of my audio session and it's configuration.  Then my AVAudioSession wouldn't be de-activated each time the FSAudioStream object is stopped.

Curious what you think about this @muhku

**Comment by muhku** [comment]
@mmcdole: Mind checking if commit fe6701a3238d1fde3febe8f85a56a36a980e276d fixes this for you? After this, no specific "hacks" should be needed anymore.

**Comment by muhku** [comment]
Added a test case in 9d235531cb24a54d6f9f84b56b560d4bffcad53c as per the steps to reproduce and playback seems OK.

**Comment by muhku** [comment]
Had a mistake with the locks so ae17699be561d72b2cb95f371b996ab9bb2bc466 needs to be picked in as well. Hopefully all good now.
