### ISSUE TITLE
Stream runs out of data

### ISSUE THREAD

**Issue by nanako-sen** [muhku/FreeStreamer#154]
Hi,

When streaming a securenet stream (radio stream, also never ending) the stream just stops playing, some times sooner sometimes later. This is the debugger output (using latest version):

run out of data to provide for encoding
6144 output bytes available for the audio queue
Found the last packet to be cleaned up
Cache underflow, enabling the HTTP stream
audioQueueTimerCallback called
virtual void astreamer::Audio_Stream::audioQueueBuffersEmpty(): enter
0 cached packets, enqueuing
virtual void astreamer::Audio_Stream::audioQueueBuffersEmpty(): closing the audio queue
void astreamer::Audio_Stream::close(bool): enter
Releasing audio queue
void astreamer::Audio_Stream::close(bool): leave

Any tips on how to prevent this from happening? 
Please let me know if you need more information.

Cheers

**Comment by mmcdole** [comment]
@nanako-sen what version of FreeStreamer are you using? Version 2.10.2 will now attempt to restart a stream on network failure.  Not sure if that would help in your situation or not.

**Comment by nanako-sen** [comment]
I am using Version 2.10.2. don't think network is the issue, no networking problem reported.
In theory, what would cause the issue I am experiencing? 
Shouldn't the buffer be refilling when it's empty?

**Comment by muhku** [comment]
@nanako-sen: Looks weird. I'm suspecting that you are running into some corner case which is masking a network error. Do you mind grabbing logs again with the commit 0c2b2e9be1e7f855c48dee6fe80710c373c9a240?

**Comment by nanako-sen** [comment]
Doesn't seem to be a issue with the stream, didn't hit the new log (I copied a bit more)

8192 output bytes available for the audio queue
Found the last packet to be cleaned up
Cache underflow, enabling the HTTP stream
audioQueueTimerCallback called
Less than 128 packets queued, returning...
audioQueueTimerCallback called
Less than 128 packets queued, returning...
audioQueueTimerCallback called
Less than 128 packets queued, returning...
audioQueueTimerCallback called
Less than 128 packets queued, returning...
calling AudioConverterFillComplexBuffer
encoderDataCallback called
encoderDataCallback called
encoderDataCallback called
run out of data to provide for encoding
6144 output bytes available for the audio queue
Found the last packet to be cleaned up
Cache underflow, enabling the HTTP stream
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
audioQueueTimerCallback called
virtual void astreamer::Audio_Stream::audioQueueBuffersEmpty(): enter
0 cached packets, enqueuing
virtual void astreamer::Audio_Stream::audioQueueBuffersEmpty(): closing the audio queue
void astreamer::Audio_Stream::close(bool): enter
Releasing audio queue
void astreamer::Audio_Stream::close(bool): leave

**Comment by muhku** [comment]
According to the log this is now very clear:

<pre>
virtual void astreamer::Audio_Stream::streamEndEncountered()
</pre>

We get the kCFStreamEventEndEncountered event from the input stream which indicates the end of the stream.  The stream consumes the rest of the packets and then closes as the input stream is no longer running.

What causes the server to close the connection is not clear. kCFStreamEventEndEncountered does not indicate an error so maybe you should capture the network traffic and analyze it from that.

**Comment by muhku** [comment]
Actually it came to me, that in the case of streamEndEncountered() and a continuous stream, the streamer should raise a network error. As continuous streams are not supposed to never end. Then, the streamer will try to restart itself as a consequence.

**Comment by muhku** [comment]
The stream will raise a network error now if an end event is received for a continuous stream. Commit 52f982977c502811542541b95d6440ffbd3bb88c

**Comment by nanako-sen** [comment]
Thank you heaps, I'll investigate the issue with the stream and update the code. Good work!
