### ISSUE TITLE
Cache Seek Regressions

### ISSUE THREAD

**Issue by mmcdole** [muhku/FreeStreamer#155]
I've seen seeking regressions in v2.10.2.  I suspect these are related to the recent buffer seeking changes, but I haven't been able to confirm it.

I'm struggling to get solid information to report on consistent steps to reproduce.

If I seek frequently, alternating between extreme ends of a file, eventually one of 2 things will happen:

1.  A short audio sample repeats endlessly, playing the same sound over and over.  Nothing I do will recover playback short of starting a new audio stream.  No error is reported.

2.  The stream will fail with the following error message:

```
FSAudioStream: Network error: Failed to retrieve seeking position [FreeStreamer 2.10.2] URL: https://put.io/v2/files/271273879/download?oauth_token=censored
bufferCount: 8
bufferSize: 32768
maxPacketDescs: 512
decodeQueueSize: 128
httpConnectionBufferSize: 1024
outputSampleRate: 44100.000000
outputNumChannels: 2
bounceInterval: 10
maxBounceCount: 4
startupWatchdogPeriod: 30
maxPrebufferedByteCount: 10000000
format: formatID: .mp3, sample rate: 48000.000000
userAgent: FreeStreamer/2.10.2 (iOS 8.1.3)
cacheDirectory: /var/mobile/Containers/Data/Application/FB463D33-AC73-4AFD-A753-C3B9F86F6BAD/Documents
predefinedHttpHeaderValues: (null)
cacheEnabled: NO
seekingFromCacheEnabled: YES
maxDiskCacheSize: 100000000
requiredInitialPrebufferedByteCountForContinuousStream: 100000
requiredInitialPrebufferedByteCountForNonContinuousStream: 50000
2015-02-03 13:57:37.083 Unify[2104:649296] FSAudioStream: Attempting restart.
```

It seems to happen more when I seek towards the extreme end or beginning of an MP3, but I have had it happen (rarely) within the middle of the stream.  I don't know if this is a coincidence or not.  Perhaps the issue is related with me seeking to an area outside of the buffered area?  

I'm sorry I don't have more information.  I'm going to attempt to do a git-bisect later and see if I can help hone in on the offending commits that introduced the regression.

Edit:

I've been able to get it to happen fairly consistently seeking backwards within the buffer in my testing tonight as well.  I'll get the repeating sound for a bit, then the stream fails.

I'll keep playing with it.

**Comment by F1NaL** [comment]
I catch this trouble often

**Comment by mmcdole** [comment]
I've been able to get it to happen fairly consistently seeking backwards within the buffer in my testing tonight as well.

I'll get the repeating sound for a bit, then the stream fails.

**Comment by mmcdole** [comment]
I'm pretty sure I have at least one way to consistently cause this to happen:

Steps to reproduce:

1.  Once playback starts, immediately seek to 2/3 into the scrubber.
2.  Once playback resumes, immediately seek backward to an area that had not yet buffered at the beginning of the song during Step 1 (say about 1/5 into the scrubber).
3.  Notice the repeating sound and then stream crash.

I've gotten so that I can do this fairly consistently.

This isn't the only way to make this issue occur, but this is one way.  I've had it happen seeking forward in the stream too.

**Comment by mmcdole** [comment]
I've been testing the released versions of FreeStreamer in my project and attempting to reproduce it:

- 2.9.17 - BAD
- 2.9.14 - BAD
- 2.9.13 - BAD
- 2.9.12 - GOOD

**Comment by sadhiappan** [comment]
Thanks for taking time to troubleshoot this issue @mmcdole. I have been running on this issue as well but I wasn't able to consistently reproduce it. 

@muhku the changes in your latest pod are really good, if you can fix this seek issue. It would be great! Thanks again for the good work!

**Comment by muhku** [comment]
Thanks for tracing this. The change between 2.9.12 and 2.9.13 is that seeking from the memory buffers was enabled. So it seems that the bug is in the cached seeking. As a workaround, you can disable the memory seeking (set seekingFromCacheEnabled = FALSE) and everything should work as before: https://github.com/muhku/FreeStreamer/blob/master/Common/FSAudioStream.h#L186 Just seeking will be slower after that.

One thing I still want to ask: does the bug still occur with the latest release 2.10.3? @hearther discovered one bug from the cache cleanup which was hopefully fixed in commit 4cb3531ae04570c71035fde9ca9508e2869e6fb1

**Comment by muhku** [comment]
And one more thing, if this still reproduces with the latest version, it would be very helpful to have logs from audio_stream.cpp with the AS_DEBUG macro enabled. Uncomment this line: https://github.com/muhku/FreeStreamer/blob/master/astreamer/audio_stream.cpp#L26

**Comment by muhku** [comment]
I made two changes in commit 826d2bf614b8c9bdd25c0ad00b7749d5d55eb044:
1) Make sure there are no races so we explicitly want to make sure the stream is playing when the seek is performed
2) Disallow memory based seeking when hitting almost the end of the buffering region.

**Comment by mmcdole** [comment]
@muhku,

Just tested ```2.10.3``` and I still see the issue.  I enabled ```AS_DEBUG``` and this is my log file before the stream crash:

https://gist.githubusercontent.com/mmcdole/8154cd0b52150d4acb95/raw/gistfile1.txt

**Comment by muhku** [comment]
@mmcdole: According to the log, seeking from the memory buffers was not used:

<pre>
Seeked packet not found from cache, reopening the input stream
</pre>

Seek was performed two times and at the 2nd time something went wrong. The first time when there is data to feed to the audio queue:

<pre>
[audio_stream.cpp:1328 thread 807] 8192 output bytes available for the audio queue
</pre>

The queue just keeps rejecting the data:

<pre>
[audio_stream.cpp:1227 thread 807] Queue cannot accept packets, return
</pre>

**Comment by mmcdole** [comment]
I guess when the queue is rejecting the data.. that is when I'm hearing the repeating sound over and over?  This happens until the eventual stream crash.

I can make this happen for both local files and for remote files as well.

**Comment by muhku** [comment]
Yes, that's the repeating sound. A unit test case would be really helpful if the issue could be reproduced in that way.

**Comment by mmcdole** [comment]
@muhku I spent awhile trying to write a unit test for this.  I've not had any luck getting a test to reproduce the issue.

I even tried writing my test as sort of a fuzzer where it attempts to seek after a random delay, to a random position, repeatedly.

Trying to see what conditions are different in the tests that would make this issue not occur..  I have an 10MB buffer in my project, while I have left the unit test with the default streamConfig.  Not sure what other differences there might be.

**Comment by Gurpartap** [comment]
I'm able to reproduce the same issue when I try to seek back and forth consecutively within buffered audio. A short audio sample repeats endlessly. I haven't faced the error described in (2) in the topmost post, yet.

And I can confirm that it occurs only when seekingFromCacheEnabled is configured to YES.

**Comment by Gurpartap** [comment]
Well, not exactly endlessly. It sometimes resumes playing after a while, and some times stops. https://www.youtube.com/watch?v=1vdxqqFUJ1w

**Comment by muhku** [comment]
Thanks @mmcdole and @Gurpartap

Now the most helpful thing would be to identify how to reproduce this consistently. Can possibly one these sample files reproduce it?

* https://dl.dropboxusercontent.com/u/995250/FreeStreamer/5sec.mp3
* https://dl.dropboxusercontent.com/u/995250/FreeStreamer/As%20long%20as%20the%20stars%20shine.mp3

If so, let's stick to one sample file and after that, we can try to identify how to reproduce the issue using that one specific file.

Good work so far!

**Comment by mmcdole** [comment]
I'll try both of these files today and try and reproduce the issue.

**Comment by muhku** [comment]
Reverted the previous change. Don't think this had anything to do with the memory buffer seek after all. I think there's some race condition which is randomly triggered and the audio queue gets messed up because of that. So as per commit 482fd693a2ab623d34acdd6149ac4952a4845b09 the input stream is disabled during a seek which at least shouldn't make anything worse. Also added a check that we don't try to enqueue cached data during a seek.

**Comment by muhku** [comment]
Argh, seems that my previous commit just messed up the seeking more than before. Hope this approach finally makes sense. Squashed the changes in commit 947b16328ee783530eee40628a8bf0efd5050adb

The idea is that we try to avoid any potential races by closing the audio queue immediately when we start seeking and also disable the input stream.

**Comment by muhku** [comment]
In my testing with 2.10.4 (which contains the aforementioned commits) I didn't notice the seeking problems anymore. Feel free to reopen / comment here if the problems still occur.

**Comment by Gurpartap** [comment]
Still occurs. I'll get back with a sample project.

**Comment by muhku** [comment]
OK. Reopening.

**Comment by mmcdole** [comment]
@muhku, I re-enabled cacheSeeking and tried out 2.10.4.  I've been unable to reproduce the bug.

Nice work!

**Comment by muhku** [comment]
OK, I'll close this then as @mmcdole was the original reporter and it seems to work for him now. But please keep your observations coming. I have really hard time reproducing this myself (actually unable to reproduce) so sample code would be appreciated if you are still having problems.

**Comment by muhku** [comment]
Btw, added a simple test case for seeking in commit a56c0ac7066397c68219014d353f5931158ab15b

The test case seeks 50 times in a row and waits 0.3 seconds between each seek. The seek offset is 0.1 and 0.9 in every other seek request. Hope that helps as well for identifying any further problems.

**Comment by Gurpartap** [comment]
Oh? I have my doubts on my implementation now. Either way, I can still reproduce it with this sample project: https://github.com/Gurpartap/FreeStreamerSeekTest

**Comment by Gurpartap** [comment]
Video: http://www.youtube.com/watch?v=fW_DvbarN2I

**Comment by Gurpartap** [comment]
FYI, I patched `FSFrequencyPlotView.h` to add `#import <UIKit/UIKit.h>` so that it compiles.

**Comment by muhku** [comment]
@Gurpartap: I run your sample code and couldn't reproduce the problem like in your video. Weird. Fixed the missing UIKit import.

**Comment by mmcdole** [comment]
@muhku, I loaded @Gurpartap's project onto my iPhone and was able to reproduce the issue he demonstrated in the video.

**Comment by mmcdole** [comment]
@muhku @Gurpartap I'm unable to reproduce it in my own project streaming the same file in @Gurpartap's demo project.

Some differences between our projects:

* When I seek in my project, I use minute/second instead of ```position```.
* My cache amount is set higher than the default (5MB right now)

Haven't had time to look for other differences.

**Comment by mmcdole** [comment]
@Gurpartap can you try modifying your sample code to any of the above differences and see if you still have the issue?

**Comment by syrakozz** [comment]
+1

**Comment by muhku** [comment]
Let's continue the investigation in new issues & preferably if still problems, please reproduce using the bundled unit tests or the FreeStreamer demo project. Thanks.
