### ISSUE TITLE
stream faster

### ISSUE THREAD

**Issue by syrakozz** [muhku/FreeStreamer#157]
could you plz make the stream faster,
other famous library on github use AudioUnit API rather than the slower AudioQueues API , and its really stream fast, 
is there any way you can make FreeStreamer also stream faster, 
thank you

**Comment by muhku** [comment]
I think the perceived slowness might be due the FSAudioController usage. FSAudioController always makes the requests to determine the content-type / playlists / resolve RSS feeds, etc., so it is not as fast FSAudioStream. So for faster streaming please use FSAudioStream.

**Comment by syrakozz** [comment]
@muhku  , you are right, 
could you plz add the ability to set the content type, ..... so the FSaudiocontroller dons`t need to do that work, 
in that case it will work faster,
one more thing, 
can you plz add the ability to add the playlist item manualy without resolve RSS feedd....
in my case i have some mp3 file that i would like to make them play in the controller like list of mp3 files,
did you get the case ?

**Comment by muhku** [comment]
Please check http://freestreamer.io/api/Classes/FSAudioController.html#//api/name/playFromPlaylist:

And http://freestreamer.io/api/Classes/FSAudioController.html#//api/name/playFromPlaylist:itemIndex:

Example code from the unit tests: https://github.com/muhku/FreeStreamer/blob/master/FreeStreamerMobileTests/FreeStreamerMobileTests.m#L71

<pre>
 FSPlaylistItem *item1 = [[FSPlaylistItem alloc] init];
    item1.url = [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"test-2sec" ofType:@"mp3"]];
    
    NSMutableArray *playlistItems = [[NSMutableArray alloc] init];
    [playlistItems addObject:item1];
    
    [_controller playFromPlaylist:playlistItems];
</pre>

**Comment by syrakozz** [comment]
i made 
pod update 
but i still getting version 2.11.3

**Comment by syrakozz** [comment]
thanks alot, 
but 
- (void)playFromPlaylist:(NSArray *)playlist itemIndex:(NSUInteger)index

it pass the playlist, but i already pass it in the first method ,
can we have , 
- (void)playAtIndex:(NSUInteger)index{

**Comment by syrakozz** [comment]
if you can add this method , i gguess it great 

- (void)playAtitemIndex:(NSUInteger)index
{
    [self stop];

    self.currentPlaylistItemIndex = index;
    
    self.readyToPlay = YES;
    
    [self play];
}

**Comment by syrakozz** [comment]
and can you plz make this public
@property (nonatomic,strong) NSMutableArray *playlistItems;  

so we can call it from other class ,
we need it in case we need to remove/update a specific item
or do you think to keep it private a make a method for
 delete the playlist item at index
and update at index

**Comment by muhku** [comment]
There should be specific remove/update methods in the interface for that purpose. Exposing the array is not good. I think you can add that quite easily, will try to look at that later on...

**Comment by muhku** [comment]
Some basic methods for playlist management added, commit 6186a466bd314b3d332e383db7501f2e58f26a3d

Not tagged yet. The removal is more tricky as it has so many corner cases. Let's see.

**Comment by muhku** [comment]
I made the assumption that the currently playing playback item cannot be removed. Pushed da834a20a417917d251cabd4e4caa44a8833ac64

**Comment by syrakozz** [comment]
great , and if the user was playing the item at i dex in the meanwhile if we can preload the next and the previous item will be great



—

**Comment by muhku** [comment]
See #166
