### ISSUE TITLE
issue of onCompletion 

### ISSUE THREAD

**Issue by tobatha** [muhku/FreeStreamer#160]
Pure awesome library for audio streaming

Recently i'm using this library for streaming mp3 from the server, there's a little issue going on.

If i manually go prev/next calling funcs below
[audioContrller playFromURL:_audio.mp3_url];
it can streaming from the very beginning

but when i let the audio streaming keeps on playing itself and reach playbackCompleted/onCompletion, and jump to next audio by calling the same func, it'll strangely start streaming from 1 min later, and it doesn't happen instantly, happens like playing for 1~2 sec from beginning after buffering, and then suddenly jumped to 1 min later, and keep on going

i don't know if i was doing anything wrong here, or maybe didn't clean the current playing stream before going to next url, or maybe the issue is caused from serverside.

Any suggestions are very welcome, thanks a lot !

**Comment by syrakozz** [comment]
+1

**Comment by tobatha** [comment]
@syrakozz did u encountered the same issue?

**Comment by syrakozz** [comment]
yes also

**Comment by muhku** [comment]
Cleaned up the code, commit 7d6e6881c6f907bcb36ba3a4316ee496ed9d7401

**Comment by tobatha** [comment]
@muhku Thank u so much for fixing the little bug! really appreciate it sinceriously ~ ^_^
