### ISSUE TITLE
Stream starts from background?

### ISSUE THREAD

**Issue by OliverDimitrov** [muhku/FreeStreamer#161]
Hi @muhku ,

Maybe it's not FS related issue, but maybe some of the other users had encountered.

So I open the app, play some radio stream, then stop it and put it in background (i support background mode). Then I open some other apps, or I just lock the device. After a while if I unlock the device, all of a sudden the stream just starts playing! Like it was clicked play from the remote centre, but it wasn't. 
Also, this doesn't happen all the time, it's random.

Any thought of you or some other user with this kind of experience? Any solution? 
PS: Background playing mode is a must, because it's a radio app.

Regards,
Oliver

**Comment by muhku** [comment]
It sounds like the fail-safe workaround for iOS killing the sockets in the background. Goes probably like this:

1. Stream was playing
2. iOS kills the socket
3. Playback stops -> user doesn't notice because the app is in background
4. FreeStreamer restarts the stream as a fail-safe measurement when the app activates again

The line doing the restart is this: https://github.com/muhku/FreeStreamer/blob/master/Common/FSAudioStream.mm#L1434

**Comment by syrakozz** [comment]
is there any solution for this case

**Comment by OliverDimitrov** [comment]
@muhku 
It's not quite like my case. In my case I pause the stream in the app and then put it in background.

And then somehow after a while it starts again when I unlock it or press the home button. 

I've just written some code in my appDelegate in applicationDidEnterBackground where I check if the player is playing and is it in paused state, to call stop on the streamer and with that to close the stream socket.

I'll test it how it works in couple of hours and will write again.

Also I've googled it about this behaviour and found some blog posts about it:
- http://www.iphonetopics.com/ios-8-1-2-problems/ (search for text: "music starts playing after hanging up") and 
- http://forums.imore.com/iphone-5/267461-music-randomly-turns.html

So maybe it's just a apple bug that need to be fixed.

**Comment by OliverDimitrov** [comment]
Sorry for my late response.

I guess this little code I used, did the trick for me 
And @muhku for the scenario you've described it, I guess that's a valid scenario, because the user decided to leave it the stream playing. 

I guess I can close this "issue".
