### ISSUE TITLE
Convert the example project to Swift

### ISSUE THREAD

**Issue by muhku** [muhku/FreeStreamer#162]
If somebody (preferably with previous Swift experience) got some extra time on his or her hands, it would be nice that the example project would be written in Swift instead of Objective-C. That's because now Swift is the default language used by the iOS SDK.

**Comment by muhku** [comment]
Notice that the conversion is only relevant for View Controllers, everything else can be left in place as is.

**Comment by ronflima** [comment]
It is pretty easy to create a bridge from this project to Swift. I would like to help in doing such a thing.

**Comment by muhku** [comment]
Why would a bridge / wrapper needed for Swift? Objective-C code works fine from Swift. I don't like the idea of adding one more layer of complexity. We already have the core written in C++ and wrapped by Objective-C implementation. Swift would bring one more layer.

What I simply meant that have the example view controllers written in Swift. I think many people have been already doing that but the code is not published.

**Comment by ronflima** [comment]
You need a bridge in order to expose your objective c into swift. It is simply a header file. Otherwise you are unable to use objective c into swift according to apple's documentation. 

Enviado do meu iPhone

**Comment by muhku** [comment]
Yes. Then the Objective-C bridging header would be needed.

**Comment by ronflima** [comment]
That’s the point. It can be pretty simple to do. This header file can be even generated by a build script. I’ll try to create an example in swift and I’ll send the project to you.

Ronaldo Faria Lima

CSO @ |||LOUD|||
ronaldo@loud.digital <mailto:ronaldo@loud.digital>
+55 16 98136 5287
Skype: ron_lima

**Comment by muhku** [comment]
I think this can be closed for now. Pull requests can be always submitted.

**Comment by sparkxxf** [comment]
So have someone submit the swift example project now? Thank you.

**Comment by aChase55** [comment]
@ronflima are you using cocoapods or adding the FreeStreamer project to your workspace when implementing with swift?

**Comment by ronflima** [comment]
In fact I have not started to do it. No time available at all. As soon as I'll do it, probably I'll use cocoapods.

**Comment by muhku** [comment]
I think actually a more important task would be to add nullability annotations to FS public interfaces. PRs are also welcomed in this area.
