### ISSUE TITLE
All I/O should be stopped or paused prior to deactivating the audio session.

### ISSUE THREAD

**Issue by syrakozz** [muhku/FreeStreamer#163]
in the example project
when i was playing the m3u playlist , after i press previous i got  this error
ERROR:     [0x34dd79dc] AVAudioSession.mm:646: -[AVAudioSession setAct
ive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by muhku** [comment]
Cleaned up the code, commit 7d6e6881c6f907bcb36ba3a4316ee496ed9d7401

**Comment by syrakozz** [comment]
its still happen with the latert version also, 
when the item is playing you play another stream sometime 
i got 
Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session. ,
and the sound fade in  and disappear
