### ISSUE TITLE
not working with downloaded song

### ISSUE THREAD

**Issue by syrakozz** [muhku/FreeStreamer#164]
i download the song into the project
the path of the mp3 is :  
file:///var/mobile/Containers/Data/Application/A02BA232-9EDE-40B9-8F82-811192F6280E/Library/Application%20Support/file-download/9C458576-7B17-48B7-8522-7DF883EA2F91.mp3

but it crash on
return [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:fileName ofType:suffix]];

plz help

**Comment by syrakozz** [comment]
and i got 
Cannot open the audio stream:  Input stream open error

**Comment by syrakozz** [comment]
i got 
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
*** First throw call stack:
(0x246c9f87 0x3206ac77 0x246c9ecd 0x2535e37f 0x2535e2fb 0x277e03 0x263d63 0x93bf3 0x93fb7 0x27c5dfc7 0x27d0f627 0x27bc1919 0x27b3d7df 0x24690845 0x2468df29 0x2468e32b 0x245dbdb1 0x245dbbc3 0x2b90f051 0x27ba6f01 0x81d89 0x32606aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by muhku** [comment]
Please read the FAQ: https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ#how-can-i-play-local-files

**Comment by syrakozz** [comment]
yes it work when i use  [NSURL fileURLWithPath:myAudioFile];
but when i use 
return [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:fileName ofType:suffix]]; 
it crash , maybe you should fix it
