### ISSUE TITLE
FSAudioController automatic preloading for next playlist items

### ISSUE THREAD

**Issue by muhku** [muhku/FreeStreamer#166]

**Comment by muhku** [comment]
Changes in the auto-preloading branch. There could be some corner cases still but mostly seems working. Unit tests pass as well. Maybe somebody else wants to take a look as well? @mmcdole I think this should be interesting to you as well.

**Comment by syrakozz** [comment]
great :) it will be great feature,

**Comment by sohayb** [comment]
:+1:

**Comment by muhku** [comment]
Commits are in the master branch now. I'll wait a bit before tagging + releasing so you have a chance to test if there's something that's obviously broken.

Please notice that for blocks, don't use FSAudioController.stream anymore but the blocks directly offered by FSAudioController.

**Comment by syrakozz** [comment]
great,  if we can explicitly preload a specific playlist index, it will be great, 
per example maybe  if the user is on wifi i will preload 
itematindex+1  and itematinder+2 and  and itematinderx-1

**Comment by syrakozz** [comment]
is there any callback i can implement that indicate wheer the next playitem will start preload

**Comment by muhku** [comment]
Let's proceed one step at the time. I want to make sure that there are no regressions before doing further changes.

**Comment by syrakozz** [comment]
sure, i m testing the example , 
m3u playlist test, 
if you play the item ,
and press next, 
it does nothing for a while

**Comment by syrakozz** [comment]
case 2 
if you enter to m3u playlist test and play , 
while playling you press back on the nabigation while playling
then you reenter to m3u playlist
you get an error 
connot open audio stream  strict content checking active

**Comment by muhku** [comment]
Added a simple delegate for watching the preload progress, 7e53dc7669eef38d815dc3e7e0d797541fe94d4e

**Comment by muhku** [comment]
OK, there are still obvious bugs that need more work. Will move the code back to the preloading branch and then reset the master branch back to the previous release.

**Comment by syrakozz** [comment]
ok

**Comment by muhku** [comment]
Case 1 fixed. Keep your bug reports coming and break it :)

**Comment by syrakozz** [comment]
great, sure,

**Comment by muhku** [comment]
Case 2 doesn't seem to be a bug related to this. Also happens with master.

**Comment by syrakozz** [comment]
you are right, so maybe these bug are from before and the preload seems good for now

**Comment by muhku** [comment]
Got one more idea I want to implement before pushing this. It would be nice to have some mechanism for temporarily disabling the preloading. So in the delegate protocol, I will have method for overriding preload.

**Comment by syrakozz** [comment]
excellent

**Comment by muhku** [comment]
And one more issue that needs pondering: for the preloaded streams the metadata is "lost". Because the metadata is typically received in the beginning of the stream and we are not listening to the stream state when it is preloading, the metadata isn't stored to the player.

**Comment by syrakozz** [comment]
can we get the meta when the preload stream play(listen) like the current stream , 
maybe we dont need the meta info when the stream is preloading , only needed when we want to playlit

**Comment by muhku** [comment]
Tagged and pushed 2.12.2. We can think about the metadata issue later. If this is a showstopper problem, FSAudioController support disabling preloading.
