### ISSUE TITLE
update playlist item

### ISSUE THREAD

**Issue by syrakozz** [muhku/FreeStreamer#167]
for the playlist thing, 
when the user play a item , he maybe want to download the media so after he downloadit i need to update the link of it so  i need to update the current playlist  item

perexample if we can have 
 updatePlaylistAtindex( int)  (playlistitem)

it will be great

**Comment by muhku** [comment]
http://freestreamer.io/api/Classes/FSAudioController.html#//api/name/replaceItemAtIndex:withItem:
