### ISSUE TITLE
onStateChange block not being called

### ISSUE THREAD

**Issue by MrAppleBR** [muhku/FreeStreamer#170]
Hello,

I can't seem to get the onStateChangeBlock to get called. Even with the simplest code, see below, it doesn't work.

#import "XX.h"
#import "FSAudioController.h"

@interface XX () <FSAudioControllerDelegate>
@property (nonatomic, strong) FSAudioController *audioController;
@end

@implementation XX

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    self.audioController = [[FSAudioController alloc] init];
    self.audioController.delegate = self;
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    
    self.audioController.onStateChange = ^(FSAudioStreamState state) {
        NSLog(@"onStateChange: %d", state);
        // this never gets called!
    };
    
    NSURL *url = [NSURL URLWithString:@"url_that_works_fine"];
    self.audioController.url = url;
    [self.audioController play];
}

@end

**Comment by muhku** [comment]
Argh, somehow missed this case when the preloading changes were done. Should be fixed as per fce326550a5cf2f299ebf09c88f37f19545f6950

Will tag and push the pod.

**Comment by muhku** [comment]
Tagged and pushed.

**Comment by MrAppleBR** [comment]
so i re installed the cocoa pods file and it came back with the same version number. Did you release a new version to the pod? when i changed manually what you did here: [fce3265](https://github.com/muhku/FreeStreamer/commit/fce326550a5cf2f299ebf09c88f37f19545f6950) it came back to work.

**Comment by muhku** [comment]
I don't why you didn't get the latest pod. I think people have been complaining the same thing before. But if you search from cocoapods.org it comes up with the latest tag 2.12.4. Double checked that 2.12.4 contains the commit. So not sure if CocoaPods is buggy or the environment / tools. Anyhow if CocoaPods doesn't work, you can always install the latest tag manually like you did.

**Comment by muhku** [comment]
![nayttokuva 2015-03-06 kello 14 48 00](https://cloud.githubusercontent.com/assets/70924/6525588/ce705b88-c40f-11e4-8857-62ca6d049ad5.png)

**Comment by MrAppleBR** [comment]
I see, maybe it was cached.. I will try the pod again to see if it goes automatically.
