### ISSUE TITLE
metering values for peak and average...

### ISSUE THREAD

**Issue by rizkhan7** [muhku/FreeStreamer#178]
I am trying to move to FreeStreamer from STKAudioPlayer, how do you capture metering data for channels? I need to look at the average or peak power for channel...thanks!

**Comment by muhku** [comment]
We currently don't do that. But you can get it with the audio queue property kAudioQueueProperty_CurrentLevelMeter and add the calls to audio_queue.cpp. Then wrap the value to the Obj-C side. There's plenty of existing code for a similar value passing.

**Comment by TheEffekted** [comment]
Could you please elaborate a bit more on how to get the power of the channel? Would that data be accessible from within the audio_queue.cpp file then?

I'm making a little wave view that dances around according to the current power of the sound.

Thanks!

**Comment by muhku** [comment]
http://muhku.github.io/FreeStreamer/api/Classes/FSAudioStream.html#//api/name/levels
