### ISSUE TITLE
The stream.duration and stream.contentLength attributes are inaccurate for some streams

### ISSUE THREAD

**Issue by davidhlee** [muhku/FreeStreamer#180]
The contentLength() method (ln. 327) in audio_stream.cpp seems to be calculating incorrectly.

For instance, for this podcast the stream.duration says the file is 65:33 long, but the actual stream is only 48:00: http://podcastdownload.npr.org/anon.npr-podcasts/podcast/344098539/397524756/npr_397524756.mp3

Similarly, for this podcast the stream.duration says it's 54:37, but it should be 53:25: http://podcastdownload.npr.org/anon.npr-podcasts/podcast/510208/397517063/npr_397517063.mp3

I tried to investigate why but my C++ is a little shaky = )..

**Comment by muhku** [comment]
If you try to stream the aforementioned files locally or from another server, is the contentLength() still incorrect?

**Comment by davidhlee** [comment]
Yes, even downloading the file locally and dropping it into the Freestreamer sample app produces the wrong contentLength (65:33 instead of 48:00).

**Comment by muhku** [comment]
Took a quick look. It seems that the files are not providing the AudioDataPacketCount header, which means that we end up using the estimation based algorithm for duration based on bit rate. Well, that's not a problem itself. But the bit rate based estimation for duration goes wrong for some reason.

Weirdly enough, VLC ended up even crashing when trying to open the files but iTunes showed that the files are in mono. Could that be the reason that the bit rate based estimation goes wrong?

**Comment by davidhlee** [comment]
So I'm not sure too be honest--I'm not too familiar with audio formats. However, I was able to find a stream that calculates the correct contentLength of 15:59 (16:22 including pre-roll commercial):

http://podcastdownload.npr.org/anon.npr-mp3/npr/blog/2015/04/20150410_blog_pmpod.mp3?orgId=1&e=398869663&d=959&ft=pod&f=510289

(http://www.npr.org/rss/podcast.php?id=510289)

Is this one mono or stereo? It gets the correct file length remotely and locally. Mono seems to be pretty prevalent for podcasts, as stereo is unnecessary: http://www.quora.com/Why-are-the-majority-of-the-Nerdist-podcasts-recorded-in-mono-instead-of-stereo.

**Comment by muhku** [comment]
Can you get the duration of the files from somewhere? I think one possibility would be to add support for duration hints in FreeStreamer, which would be used if the MP3 headers for duration are missing. Alternatively the UI could possibly even display the real duration from your own source directly, as FreeStreamer does not really need the duration for file playback.

**Comment by davidhlee** [comment]
Oh man. Yes, it appears that both these XML streams provide a "duration" tag, which I assume is in seconds: http://www.npr.org/rss/podcast.php?id=510208
http://www.npr.org/rss/podcast.php?id=344098539

Assuming these tags are widely used by all providers, this should do the trick! However, in the event that this duration tag isn't provided AND the bit rate estimation is wrong, the FreeStreamer still needs some way of calculating the duration for file playback--otherwise UISlider's don't know what to do with the excess time, and end up skipping and breaking the experience.

**Comment by muhku** [comment]
It seems that the problem occurs because the calculation didn't take meta data size into account. Please let me know if commit 73b7fc6cc29a2b90ae9165015fdbbc84c53f10d6 fixes it for you. You will need to pull the latest tree from master including the changes in the id3 parser.

**Comment by davidhlee** [comment]
Yep that fixed it as far as I can see! Thanks for being so responsive, FreeStreamer has been a great library thus far.

**Comment by muhku** [comment]
Great. Tagged 2.12.10 and pushed the POD so let's close this one for now.
