### ISSUE TITLE
Can't set requiredPrebufferSizeInSeconds

### ISSUE THREAD

**Issue by Djelibeybi** [muhku/FreeStreamer#182]
Hi,

I've been trying to increase the requiredPrebufferSizeInSeconds value via an FSStreamConfiguration object, but it doesn't seem to want to stick. I can change things like bufferSize and bufferCount, though.

I've double-checked this by using the sample project and adding ``_configuration.requiredPrebufferSizeInSeconds = 30;`` to the ``viewDidLoad`` method, but it has no effect here either.

So, it appears this configuration setting is being ignored.

**Comment by muhku** [comment]
Fixed in commit 334c5a399fd1058db7d6ae31ce6bdebc3c64d8cb

Tagged 2.12.11 and pushed the POD.

**Comment by Djelibeybi** [comment]
FYI, confirmed as working. Amazing response time, thanks. :+1:
