### ISSUE TITLE
Play local file without internet connection

### ISSUE THREAD

**Issue by AhmettKeskin** [muhku/FreeStreamer#185]
Hi All,
i m building an app that plays Mp3. User downloads some of mp3s for offline mod and what i m trying to do is when connection is lost, refresh the list with local songs and start it again. But i always get error when try to play local files without connection. Could not we use FSAudioController as a player?

![screen shot 2015-05-23 at 16 31 23](https://cloud.githubusercontent.com/assets/4210229/7784314/12749b04-016a-11e5-9be8-534daa074386.png)

When i have connection and try to play local files, it works properly. i do not know maybe there is a easy solution but i could not figure out. Do you have any suggestion ?

**Comment by AhmettKeskin** [comment]
I figured out smth. new. When i run app first time and download musics. And then try to play from local, it works perfectly. But second time or more, when i try to play downloaded musics from local , it gives error like my first post.

Anyway, i solved my problem but still it would be great if you give any suggestion for this situation

Thanks..

**Comment by ChrisWang115** [comment]
@AhmettKeskin wish i can help you.
i have the same problem,but  i found the answer.
i save this file absolute path when i first download audio.
this is the key. i should not save the absolute path. Xcode build the app generate different path everytime.
so i should just save this file name.
next time when i access to this file. and then combined them.
