### ISSUE TITLE
The last part of a short mp3 repeats a couple of times

### ISSUE THREAD

**Issue by amaldona** [muhku/FreeStreamer#186]
Hi

Recently I've started using this library for audio streaming and it's great, but I found an issue:
Playing a short mp3 (5 seconds), the player repeats the last second. I found that it only happens on FreeStreamer 2.12.7 and later, on 2.12.6 and earlier works fine.
The differences between 2.12.6 and 2.12.7 (https://github.com/muhku/FreeStreamer/compare/2.12.6...2.12.7), are basically 'usePrebufferSizeCalculationInSeconds' support and a watchdog.
I tried disabling usePrebufferSizeCalculationInSeconds with no luck:

```
    FSStreamConfiguration *config = [[FSStreamConfiguration alloc] init];
    config.usePrebufferSizeCalculationInSeconds = NO;
    FSAudioStream *audioStreamer = [[FSAudioStream alloc] initWithConfiguration:config];
```
Even tried `config.startupWatchdogPeriod = 0` (which shouldn't be disabled, but it was just a test) but nothing.

It's reproducible using the **"Test MP3 file"** from here:

https://dl.dropboxusercontent.com/u/4814602/example-rss-feed.xml  (is a copy of the rss-feed from the example, with the url of the mp3 mentioned above)

Just change the example-rss-feed.xml url in the FreeStreamerMobile example with this, and select **'Test MP3 file'**.

I tested it on iOS 7.1 and 8.3, and FreeStreamer:

2.12.11: Error
2.12.7:  Error
2.12.6:  Ok
2.12.5:  Ok
2.12.4:  Ok
2.12.3:  Ok
2.11.6:  Ok

Thanks.

**Comment by muhku** [comment]
The decoder has been revamped in the latest development version (3.0.0). Please reopen if this problem still appears.
