### ISSUE TITLE
Next song is not playing automatically

### ISSUE THREAD

**Issue by bbalachandhar** [muhku/FreeStreamer#190]
Hi,

I am trying to play the next song url automatically once the current song ended. I am calling [controller addItem:item] twice for setting two different FSPlaylistItem. But it is not working.

thanks,
bala

**Comment by humayunharoon** [comment]
@muhku same here, for me if the app is in the background state (phone locked), when a playlistItem finishes, i can see on the lock screen that it has switched to the next one (name changes) but the next song doesn't start playing. Same for when the app is in the foreground, it switches, but doesn't start playing.

**Comment by muhku** [comment]
I moved AVAudioSession handling in FSAudioController so that the audio session is kept active during a playlist item is switched. Does it help? Commit f139bd7
