### ISSUE TITLE
The infamous All I/O Error next song gets paused

### ISSUE THREAD

**Issue by humayunharoon** [muhku/FreeStreamer#191]
I am using FSAudioController and add items to its playlist, which have tracks as mp3's which are streamed off the internet. As expected some of the tracks are also cached. Whenever i press next/previous track and the track which is about to be played is cached, it plays for a second and then pauses with the AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session. error in the console. 

I can't solve the issue with the workaround suggested here #153 since i am not using an audio stream directly, instead using the AudioController. Any fixes?

EDIT: From what my understanding is, a race condition is occurring where if the next track is cached, it starts playing immediately but then its audio session is attempted to be killed off. Any idea where i should be looking @muhku ?

**Comment by zhaoxuezhi888** [comment]
+1

**Comment by zhaoxuezhi888** [comment]
the issue only happy in ios8.3 and 6 plus

**Comment by WillHu** [comment]
It also happens in iOS 8.3 and 5s.

**Comment by humayunharoon** [comment]
I tested on iOS 8.3 & iPhone 6 plus. The library code is really large, i couldn't fix it so i've shifted to using https://github.com/douban/DOUAudioStreamer for now..

**Comment by zhaoxuezhi888** [comment]
DOUAudioStreamer have more problem....

**Comment by humayunharoon** [comment]
@zhaoxuezhi888 please elaborate? Its playing music fine for now and switching tracks fine for now. Freestreamer wouldn't even play the next track in the queue if app was in the background.

**Comment by zhaoxuezhi888** [comment]
plaase see https://github.com/douban/DOUAudioStreamer/issues/79,my issue
and DOUAudioStreamer not have cache

**Comment by humayunharoon** [comment]
@zhaoxuezhi888 i have yet to come across that issue with DOUAudioStreamer, and yes i need caching but right now that race condition issue that stops the next track if its cached and the next track doesn't start playing in background mode is a real killer. If this is fixed, i will come back to Freestreamer.

**Comment by muhku** [comment]
Hello. Please try commit a3a86ad141874afb0a1b229a84242d67fc8a9e94

Added the property automaticAudioSessionHandlingEnabled. For testing, supply your own configuration where automaticAudioSessionHandlingEnabled = false and then handle AVAudioSession in your own player code.

If this is helpful, I can tag 2.13.1. I think @mmcdole requested this before.

**Comment by humayunharoon** [comment]
Will this also solve the problem of the next track not starting when the
app is in background mode (regardless if its a cached track or streaming)?
I'll give it a go. Thanks

**Comment by zhaoxuezhi888** [comment]
@muhku  I find the reason of the error,modified is following:
FSAudioStream.mm  
method:
void AudioStreamStateObserver::audioStreamStateChanged(astreamer::Audio_Stream::State state)

line:1714:update time 0.1 to 0.0
[NSTimer scheduledTimerWithTimeInterval:0.0
                                     target:priv
                                   selector:notificationHandler
                                   userInfo:nil
                                    repeats:NO];

other suggest:
update all
[[AVAudioSession sharedInstance] setActive:NO error:nil];
to 
[[AVAudioSession sharedInstance] setActive:NO withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:nil];

now not any error happen...

is this ok to modify like that?

**Comment by humayunharoon** [comment]
@zhaoxuezhi888 are you sure there are no errors now? In a queue my next song (cached) doesn't start playing automatically. I press play again and then it starts and then immediately stops because of this error. I've updated the Freestreamer code.

**Comment by eirikurorri** [comment]
I'm also hitting this issue. I think this is because `FSAudioController` handles `AVAudioSession` independently of `FSAudioStream`. So if you set `automaticAudioSessionHandlingEnabled` to `NO` on your `FSStreamConfiguration`,  `FSAudioController` can still activate and deactivate `AVAudioSession`.
