### ISSUE TITLE
why song endtime is so long?

### ISSUE THREAD

**Issue by zhaoxuezhi888** [muhku/FreeStreamer#194]
@muhku 
when I play the music file with this address:
http://m5.file.xiami.com/233/100233/477780/1770622096_11734888_l.mp3?auth_key=2109a97b06e641064a3d5903011cb0b3-1436140800-0-null
I find the endtime is wrong,I print the time in control ,it show a very long time, such as 858575733

I debug the code and find the follow code:
FSStreamPosition end = self.audioController.activeStream.duration;
this end is a very large value....

the sample url is expired one day,I can give you the newest url when you fix this problem,I do not know what happened,can you help me?

**Comment by muhku** [comment]
Seems that 2cbdd92a12e0c3992dac35d4c96a6503767e3ed3 caused a regression when you don't set a default content length.

**Comment by muhku** [comment]
Fixed in 2.13.3

**Comment by zhaoxuezhi888** [comment]
thank you very much
