### ISSUE TITLE
preload nextStream not work

### ISSUE THREAD

**Issue by ucoker** [muhku/FreeStreamer#198]
In FSAudioController.m, you set self.preloadNextPlaylistItemAutomatically = YES. It will means player will automatically preload nextStream.
But ,I  put 5 playlistItem.
And [self playItemAtIndex:0];  <------- It work.Songs were played 
[self playItemAtIndex:1]; <--------not work.Song is not playing

I know In FSAudioStream.mm
Line 970:
when i run [self playItemAtIndex:1]; 
In the "- (void)play" method, _audioStream->isPreloading() will be True.
_audioStream->startCachedDataPlayback(); will run.

so I think the question will be in "- (void)play" method.

how can i do to solve the preload nextStream?

**Comment by muhku** [comment]
I suggest to try with 3.1.0. Many improvements have been done since. Please reopen if problem still occurs.
