### ISSUE TITLE
FSAudioStream fails to play again after pausing

### ISSUE THREAD

**Issue by KiranPanesar** [muhku/FreeStreamer#201]
We're using FSAudioStream in our application to play from a remote source URL. The audio begins playing when the app launches and the user can pause playback by tapping a button.

The pause action in our app triggers the following method:

```objectivec
- (void)pause {
    if (self.streamer.isPlaying) {
        [self.streamer pause];
    }
}

```

The music pauses fine.

The user should be able to resume the playback of the audio by tapping the play button, which has an action like so:

```objectivec
- (void)play {
    [self.streamer play];
}
```

We were expecting the audio to begin playing from the point at which the player is paused. _Sometimes_, this works (maybe 1 in 10 times). The rest of the times, the audio fails to play.

I dug into the internals and noticed that when the audio fails to resume, `m_audioStreamParserRunning` from `audio_stream.cpp:160` is `TRUE`. 

As I look more at the `open()` in `audio_stream.cpp`, it looks like it's designed to start playback from the beginning, rather than simply resume a `pause`. 

So, 1) Any ideas on this bug? 2) Is there an opposite of `pause` to resume playback?

**Comment by inorganik** [comment]
The pause method is a toggle.

`[self.streamer pause];`

Call it to pause and play.

On Thursday, August 6, 2015, Kiran Panesar <notifications@github.com> wrote:

> We're using FSAudioStream in our application to play from a remote source
> URL. The audio begins playing when the app launches and the user can pause
> playback by tapping a button.
>
> The pause action in our app triggers the following method:
>
> - (void)pause {
>     if (self.streamer.isPlaying) {
>         [self.streamer pause];
>     }
> }
>
> The music pauses fine.
>
> The user should be able to resume the playback of the audio by tapping the
> play button, which has an action like so:
>
> - (void)play {
>     [self.streamer play];
> }
>
> We were expecting the audio to begin playing from the point at which the
> player is paused. *Sometimes*, this works (maybe 1 in 10 time). The rest
> of the times, the audio fails to play.
>
> I dug into the internals and noticed that when the audio fails to resume,
> m_audioStreamParserRunning from audio_stream.cpp:160 is TRUE.
>
> As I look more at the open() in audio_stream.cpp, it looks like it's
> designed to start playback from the beginning, rather than simply resume a
> pause.
>
> So, 1) Any ideas on this bug? 2) Is there an opposite of pause to resume
> playback?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/muhku/FreeStreamer/issues/201>.
>


-- 
Sent from Gmail Mobile

**Comment by lkraider** [comment]
See #88 , the player should expose the isPaused state, otherwise calling code has to keep track externally which could lead to inconsistency.

**Comment by KiranPanesar** [comment]
Ah, perfect. Thanks. Closing this now.
