### ISSUE TITLE
Does not  play in background mode

### ISSUE THREAD

**Issue by ismailismail** [muhku/FreeStreamer#204]
I have added Required background modes to info.plist but it doest play in background mode. I have tested in simulator it work fine in background mode but when I try to in real device (iPhone 6 ios 8.1) it doest work. İs there bug or something that I missed. Thanks in advance.

**Comment by ericcbm** [comment]
Try to put this in your viewWillAppear:
```objective-c
AVAudioSession *audioSession = [AVAudioSession sharedInstance];
    
NSError *setCategoryError = nil;
BOOL success = [audioSession setCategory:AVAudioSessionCategoryPlayback error:&setCategoryError];
if (!success) { /* handle the error condition */ }
    
NSError *activationError = nil;
success = [audioSession setActive:YES error:&activationError];
if (!success) { /* handle the error condition */ }
```

**Comment by retendo** [comment]
Solves the problem for me. Thanks for helping!

**Comment by muhku** [comment]
This was a regression from f139bd7fc4865b1bc47dae8ad901d61c243813d6 in FSAudioController.

Should be fixed now.

**Comment by corymsmith** [comment]
Is the viewWillAppear code required with this fix?
