### ISSUE TITLE
FreeStreamer begins to play automatically even if was paused by user

### ISSUE THREAD

**Issue by ren6** [muhku/FreeStreamer#211]
Hi! Great library! However I found a big issue which is still present.
With wifi connected:
1. In your example open any radio stream and begin to listen.
2. Tap to pause
3. Drag control center from the bottom
4. Turn off wi-fi
5. iPhone will switch to Cellular network
6. Observe that FreeStreamer attempts to restart and begins to play even if playback was previously paused by user

**Comment by muhku** [comment]
Fix pushed.
