### ISSUE TITLE
NSURLConnection is deprecated in OS X 10.11, iOS 9 and tvOS 9

### ISSUE THREAD

**Issue by Djelibeybi** [muhku/FreeStreamer#216]
OS X: https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLConnection_Class/index.html#//apple_ref/doc/uid/20001697-SW16 

iOS: https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSURLConnection_Class/index.html#//apple_ref/doc/uid/20001697-SW16

It seems `NSURLConnection initWithRequest:` method has been deprecated in favour of NSURLSession instead.

Using FreeStreamer on tvOS throws the following warnings:
```
3rd Party/FreeStreamer/Common/FSParsePlaylistRequest.m:44:48: 'initWithRequest:delegate:' is deprecated: first deprecated in tvOS 9.0 - Use NSURLSession (see NSURLSession.h)
3rd Party/FreeStreamer/astreamer/http_stream.cpp:356:24: 'CFReadStreamCreateForHTTPRequest' is deprecated: first deprecated in tvOS 9.0 - Use NSURLSession API for http requests
3rd Party/FreeStreamer/astreamer/http_stream.cpp:361:29: 'kCFStreamPropertyHTTPShouldAutoredirect' is deprecated: first deprecated in tvOS 9.0 - Use NSURLSession API for http requests
3rd Party/FreeStreamer/astreamer/http_stream.cpp:366:45: 'kCFStreamPropertyHTTPProxy' is deprecated: first deprecated in tvOS 9.0 - Use NSURLSession API for http requests
3rd Party/FreeStreamer/astreamer/http_stream.cpp:404:90: 'kCFStreamPropertyHTTPResponseHeader' is deprecated: first deprecated in tvOS 9.0 - Use NSURLSession API for http requests
3rd Party/FreeStreamer/Common/FSXMLHttpRequest.m:53:48: 'initWithRequest:delegate:' is deprecated: first deprecated in tvOS 9.0 - Use NSURLSession (see NSURLSession.h)
```

It would be super peachy keen if this could be fixed in a future version of FreeStreamer. Note these are just warnings and FreeStreamer does work correctly on an Apple TV.

**Comment by muhku** [comment]
This is something we should get fixed. Sadly, I have been very busy with other stuff recently. Meanwhile, if anybody got time to look into this, patches are welcome :)

**Comment by Djelibeybi** [comment]
If no-one else picks this up in the next couple of weeks, I'll take a look at this. I'm flat out for the next couple of weeks, but should have time after that.

**Comment by muhku** [comment]
Merged the PRs from @corymsmith so this should be complete now. I'm not sure if Apple has provided a real replacement for the Core Foundation read stream API, so those have to stay for a while, until replacement has been identified.
