### ISSUE TITLE
Doesn't work when the screen is switched off

### ISSUE THREAD

**Issue by gerchicov-bp** [muhku/FreeStreamer#217]

**Comment by Djelibeybi** [comment]
You need to enable Background Audio for the player to continue when the device is locked.

**Comment by gerchicov-bp** [comment]
I found the following with magic number 4096:
https://developer.apple.com/library/mac/technotes/tn2321/_index.html
so sometimes your option is not enough

**Comment by Djelibeybi** [comment]
That is for OS X, not iOS.

**Comment by gerchicov-bp** [comment]
I didn't remember where I saw it on developer forums but it was helpful to increase the buffer size for iOS

**Comment by muhku** [comment]
This is documented in the wiki: https://github.com/muhku/FreeStreamer/wiki/Using-the-player-in-your-own-project

Closing for now.
