### ISSUE TITLE
audioStream play/pause problem

### ISSUE THREAD

**Issue by blackmatch** [muhku/FreeStreamer#222]
when I call the function [audioStream play], I need to call the function [audioStream pause] twice, then the music pause.Then need to call the function [audioStream play] twice, music play.

**Comment by dansinclair25** [comment]
I had a similar problem to this, but fixed it by only ever using [audioStream pause] to play and pause.

**Comment by pajai** [comment]
Also getting this problem.

**Comment by muhku** [comment]
I think we got recently some fixes for pausing, so please try with the latest version. See #252 thanks

**Comment by wilSonXj** [comment]
still getting this problem in 3.7.2 using Cocospod & swift 3.0
I need call `stream.pause()` in my `play fucntion` to solve this problem like this
```
 func play() {
     stream.pause()
     stream.play()
 }
````

**Comment by commando24** [comment]
I am still facing this issue in version 3.7.3. @muhku please look into this.
