### ISSUE TITLE
AVAudioSession.mm:697: -[AVAudioSession setActive:withOptions:error:]

### ISSUE THREAD

**Issue by ldjhust** [muhku/FreeStreamer#223]
I met this error when I switch to the next song:

[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

here is my switch code:

- (void)nextSong {
  // 停止正在播放的歌曲
  [audioStream_ stop];

  // 初始化歌曲
  [backgroundView_ songInfoInitial];
  // 播放歌曲
  [self playSong];
}

can somebody help me ? very thank you

**Comment by muhku** [comment]
The audio session must be kept active when a song is switched. Two options: use FSAudioController which handles this automatically or create a FSAudioStream configuration which sets automaticAudioSessionHandlingEnabled to NO and handle the audio session by yourself.

**Comment by rickyjwhong** [comment]
Hello, 

awesome player so far. I am using FSAudioController, and this is still happening. any idea? Using a playlist with FSPlaylistitem.

**Comment by commando24** [comment]
@muhku i am still having this issue.
i am using FSAudioController with playlist in which i have set configuration with automaticAudioSessionHandlingEnabled to true.
