### ISSUE TITLE
Expected expression in audio_stream.cpp

### ISSUE THREAD

**Issue by AlvaroMolano** [muhku/FreeStreamer#225]
When initialising PTHREAD I found it should be casted to be able to be used.
 
I changed
 m_converterHasData(PTHREAD_COND_INITIALIZER),
    m_converterMutex(PTHREAD_MUTEX_INITIALIZER),
    m_packetQueueMutex(PTHREAD_MUTEX_INITIALIZER),

to this
 m_converterHasData((pthread_cond_t)PTHREAD_COND_INITIALIZER),
    m_converterMutex((pthread_mutex_t)PTHREAD_MUTEX_INITIALIZER),
    m_packetQueueMutex((pthread_mutex_t)PTHREAD_MUTEX_INITIALIZER),

Just check if you need to make this change in your code.
Regards.

**Comment by muhku** [comment]
Fixed in 3.0.2
