### ISSUE TITLE
Duplicate symbols for Reachability dependency

### ISSUE THREAD

**Issue by tizkka** [muhku/FreeStreamer#226]
Hi, you should prefix Reachability dependency like said here.

https://guides.cocoapods.org/using/troubleshooting.html

**Comment by juanpare** [comment]
These could be great, I have a lot of errors for the same reason.

**Comment by muhku** [comment]
What kind of errors you are getting?

**Comment by juanpare** [comment]
Is not an appodeal error, I am using freestreamer pod and they have
reachability as dependency, that generate the duplicate errors.

I will try other way today

**Comment by juanpare** [comment]
Sorry, the other answer is not for you.

The error is a duplicate symbol in Reachability, I think that Reachability
class should hace a prefix because a lot of librariew use it.

**Comment by muhku** [comment]
Yes. We had Issue #102 for this before, when Reachability was removed from the sources so that it doesn't conflict. I don't understand how something that doesn't exists can conflict so that's why the exact error messages are needed.

**Comment by juanpare** [comment]
Maybe the problem is for the appodeal library that I am trying to install.
Here is the error message, thanks for your time.

duplicate symbol _kReachabilityChangedNotification in:
    /Users/juanpare/Library/Developer/Xcode/DerivedData/Radio-dwedfonufkenypacphojuctaxzkk/Build/Products/Debug-iphoneos/libReachability.a(Reachability.o)
    /Users/juanpare/Dropbox/Freelance/Radio/app/Radio/Pods/FacebookAdsSDK/FacebookAdsSDK.framework/FacebookAdsSDK(FBAdReachability.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by muhku** [comment]
FreeStreamer doesn't define the symbol kReachabilityChangedNotification so the duplicate must come from somewhere else.
