### ISSUE TITLE
when  seekToPosition:

### ISSUE THREAD

**Issue by zhangshijian** [muhku/FreeStreamer#228]
when   audio  seek   ，the  audio  maybe stuck,  How kil this?  thanks

**Comment by muhku** [comment]
Hi. This might be a duplicate to Issue #227 Please try with 3.0.11.

**Comment by muhku** [comment]
Pushed 3.0.15 with commit d6a830ff8fa7f9bd5d8b0d424ab3b91a5dfd29db

Let me know if still problems.

**Comment by zhangshijian** [comment]
a  mp3  file  has  cached  completed  ,  then  , i close  the  network,  but  stream  doesn't work  .  And  i also have  find  that   state  of  the stream   sometime  will  Directly change  to  EndOfFile  ,the  stream   has paused

**Comment by zhangshijian** [comment]
when  seeking,  state of the stream sometime will Directly change to EndOfFile ,the stream has paused

**Comment by zhangshijian** [comment]
if stream is playing   ,   when  state   change to  EndOfFile   ,     state of stream  also should be playing

- (BOOL)isPlaying
{
    return (_audioStream->state() == astreamer::Audio_Stream::PLAYING);
}

**Comment by muhku** [comment]
Nice catch, @zhangshijian Could you check if commit cc1c511763aed552cc9ffb3729bd2c9de52d185e helps?

**Comment by zhangshijian** [comment]
OK,i will do .     after seeking  ,   output  "[audio_stream.cpp:764 thread b07] Audio queue run out data, starting buffering", the stream  work well  and is playing ,but  state change to  buffering  , after change to EndOfFile   ,

**Comment by zhangshijian** [comment]
a mp3 file  has cached, i want to use the  cache,    Interrupted network connections , but stream can not start work   。

**Comment by zhangshijian** [comment]
sometimes, while the app switch to background, the stream will suffer some stuck. How can I fix it?

**Comment by muhku** [comment]
Pushed ef29558147d1ca5c7acbc17dc256375d3fdb234e in 3.0.17 for the buffering state fix.

**Comment by muhku** [comment]
Please reopen if this still occurs with 3.1.0.

**Comment by zhangshijian** [comment]
OK，i  will try。

**Comment by zhangshijian** [comment]
hi，muhku，  it doesn't work well   when  seek 。 i am learning  about  Core Audio ，now， i  don‘t know the difficulty of this issue  。And  i try to  develop a simple local audio player with  Audiotoolbox，i hope i can  learn more from here，thanks。

**Comment by muhku** [comment]
There was another regression discovered in Issue #241, fix now in 3.1.1

**Comment by 4Cyril** [comment]
@muhku When I call seekToPosition api， it always play from the beginning。
mp3 URL: http://ls-book.leimans.com/common/groups/63/4ec6cb015466e893f2358ffd267b295f.mp3
