### ISSUE TITLE
some  deficiency   ，i hope  i can  learn more about it   here, thanks

### ISSUE THREAD

**Issue by zhangshijian** [muhku/FreeStreamer#231]
Hi，muhku,  FreeStream  is so great。  I admired you  so much  ,  But  i  rencently  use it   , i find some deficiency  .   I was a beginner,  And  Describe the problem is not clear，forgive me。(my  english is not good).    
when i  use   seekToPosition:       

log it : 

void Audio_Stream::seekToOffset(float offset)
{
    if (state() != PLAYING) {
        // Do not allow seeking if we are not currently playing the stream
        // This allows a previous seek to be completed
        return;
    }
    
    m_inputStream->setScheduledInRunLoop(false);
    
    // Close the audio queue so that it won't ask any more data
    closeAudioQueue();
    
    setState(SEEKING);
    
    Input_Stream_Position position = streamPositionForOffset(offset);
    
    if (position.start == 0 && position.end == 0) {
        closeAndSignalError(AS_ERR_NETWORK, CFSTR("Failed to retrieve seeking position"));
        return;
    }
    
    UInt64 originalContentLength = m_contentLength;
    
    const float duration = durationInSeconds();
    const double packetDuration = m_srcFormat.mFramesPerPacket / m_srcFormat.mSampleRate;
    
    printf("22222222222222\t");
    
    if (packetDuration > 0) {
        UInt32 ioFlags = 0;
        SInt64 packetAlignedByteOffset;
        SInt64 seekPacket = floor((duration * offset) / packetDuration);
        
        m_packetIdentifier = seekPacket;
        
        OSStatus err = AudioFileStreamSeek(m_audioFileStream, seekPacket, &packetAlignedByteOffset, &ioFlags);
        if (!err) {
            position.start = packetAlignedByteOffset + m_dataOffset;
            
            printf("111111111111111\t");
            
        } else {
            closeAndSignalError(AS_ERR_NETWORK, CFSTR("Failed to calculate seeking position"));
            return;
        }
    } else {
        closeAndSignalError(AS_ERR_NETWORK, CFSTR("Failed to calculate seeking position"));
        return;
    }
    
    Stream_Configuration *config = Stream_Configuration::configuration();
    
    // Do a cache lookup if we can find the seeked packet from the cache and no need to
    // open the stream from the new position
    bool foundCachedPacket = false;
    queued_packet_t *seekPacket = 0;
    
    if (config->seekingFromCacheEnabled) {
        queued_packet_t *cur = m_queuedHead;
        while (cur) {
            if (cur->identifier == m_packetIdentifier) {
                foundCachedPacket = true;
                seekPacket = cur;
                break;
            }
            
            queued_packet_t *tmp = cur->next;
            cur = tmp;
        }
    } else {
        AS_TRACE("Seeking from cache disabled\n");
    }
    
    if (!foundCachedPacket) {
        AS_TRACE("Seeked packet not found from cache, reopening the input stream\n");
        
        // Close but keep the stream parser running
        close(false);
        
        m_bytesReceived = 0;
        m_bounceCount = 0;
        m_firstBufferingTime = 0;
        m_bitrateBufferIndex = 0;
        m_initializationError = noErr;
        m_converterRunOutOfData = false;
        m_discontinuity = true;

        bool success = m_inputStream->open(position);
        
        if (success) {
            setSeekOffset(offset);
            setContentLength(originalContentLength);
            
            m_inputStreamRunning = true;

        } else {
            closeAndSignalError(AS_ERR_OPEN, CFSTR("Input stream open error"));
            return;
        }
    } else {
        AS_TRACE("Seeked packet found from cache!\n");
        
        // Found the packet from the cache, let's use the cache directly.
        
        m_playPacket    = seekPacket;
        m_discontinuity = true;
        
        setSeekOffset(offset);
    }
    
    audioQueue()->init();
    
    setState(BUFFERING);
    
    m_inputStream->setScheduledInRunLoop(true);
}

the  console   printf   ："22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	22222222222222	111111111111111	  ...... "      Has been circulating。    i  dont  konw  why   , please   help me   thanks  !

**Comment by zhangshijian** [comment]
if  FreeStream  work well  ， it  will   Run the method once，  but   sometime   will be  circulating。

**Comment by zhangshijian** [comment]
when  seek   faild    ,  it  has the  way  to  play  with  last progress?

**Comment by zhangshijian** [comment]
good   the  new FreeStream   ,   i  hope  make  friend with you.

**Comment by muhku** [comment]
Let's keep the seeking issues in #228
