### ISSUE TITLE
Dynamic Framework Support

### ISSUE THREAD

**Issue by jaybowong** [muhku/FreeStreamer#235]
I recently changed deployment target to iOS 8.0. `use_frameworks!` configuration was added to Podfile. 

I followed [I get a build error when installed from CocoaPods](https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ#i-get-a-build-error-when-installed-from-cocoapods) but still failed. Also tried the steps in [Using the player in your own project](https://github.com/muhku/FreeStreamer/wiki/Using-the-player-in-your-own-project). And set `Enable Bitcode` to `NO`.

![](https://cloud.githubusercontent.com/assets/1948533/12002104/8e64b8fe-ab31-11e5-8d02-c8af5b4f7dd0.jpg)

Did I do it right? Or currently dynamic framework not supported?
Please help. Thanks.

**Comment by muhku** [comment]
It would be really nice to start moving to this direction that we could support framework builds. The first step would be to figure out if it means some changes to the source code.

I'll mark this as open for contributions, if somebody got time, a PR would be welcome!

**Comment by grosch** [comment]
+1 for this.  I was just about to submit the exact issue.   Not seeing a way to upvote this specifically.

**Comment by muhku** [comment]
Dynamic framework is supported since v3.5.0. Checkout the master branch or tag and drop FreeStreamer.framework to your Xcode project.
