### ISSUE TITLE
Memory leaks when profiling using instruments

### ISSUE THREAD

**Issue by corymsmith** [muhku/FreeStreamer#237]
This is on iOS9 on an iPhone 6S. 

![screenshot 2015-12-27 16 51 51](https://cloud.githubusercontent.com/assets/7315/12012617/a40811a8-acba-11e5-98f0-ddcd32a0ffff.png)

**Comment by muhku** [comment]
Pushed b493eb1a8b737d278c26c91790dc7f90a7168506 in 3.0.17. It should fix this.

**Comment by corymsmith** [comment]
This is great, thanks!
