### ISSUE TITLE
How to seekToPosition to an unloaded position?

### ISSUE THREAD

**Issue by YoungLion** [muhku/FreeStreamer#241]
When I am playing a very long streaming file, seeking the stream to an unloaded position will cause the stream to play from the beginning? How to fix this?

**Comment by corymsmith** [comment]
I'm seeing this as well with the latest commits from a couple hours ago. Seeing this in the logs: FSAudioStream: Stream terminated: Stream terminated abrubtly [FreeStreamer 3.0.20]

**Comment by corymsmith** [comment]
I just added this to my code which seems to work. It doesn't call seek if they try to seek past the currently loaded position.

In this case, `seekTo` is the ratio of the seek position to the total length.

```objectivec
float ratio = (float)self.audioController.activeStream.prebufferedByteCount / (float)self.audioController.activeStream.contentLength;
    
    if(ratio >= seekTo) {
        FSStreamPosition pos = {0};
        pos.position = seekTo;        
        [self.audioController.activeStream seekToPosition:pos];
    }
```

**Comment by corymsmith** [comment]
Wondering if this should be part of FreeStreamer, what are your thoughts @muhku?

**Comment by muhku** [comment]
@corymsmith: Sounds good.

**Comment by muhku** [comment]
Pushed cb0b9d26748fd3b283ff4483f57c9f5ecdb383c1 in 3.1.1. This should fix the problem.
