### ISSUE TITLE
EXC_BAD_ACCESS when deactivating inactive streams

### ISSUE THREAD

**Issue by corymsmith** [muhku/FreeStreamer#243]
I have a playlist of 20 items, I hit next every few seconds until the 12th item then it crashed when it attempted to deactivate the inactive streams.

![screenshot 2016-01-02 12 34 20](https://cloud.githubusercontent.com/assets/7315/12075870/2d1a911e-b14d-11e5-9ffa-33f36451f70e.png)

And here's the call stack: 
![screenshot 2016-01-02 12 35 15](https://cloud.githubusercontent.com/assets/7315/12075878/70d65ca8-b14d-11e5-8514-dfdd92172d4c.png)

**Comment by muhku** [comment]
Pushed 7aca3f23db9b457c5c56bb79a42743dac166c9d6. It would be handy to have a test case for playlists. Say 20 items like you have and then keep shuffling them 50 times so that we see that nothing goes amiss.

**Comment by muhku** [comment]
Test case added in c277a8ea89797c9b542a8882d7bd7bb206297db5

**Comment by muhku** [comment]
Fixes released in v3.1.1.
