### ISSUE TITLE
Playback stutters for 3/4 secs when screen locks or app goes to background

### ISSUE THREAD

**Issue by sifulony** [muhku/FreeStreamer#244]
Playback stutters for 3/4 secs when screen locks or app goes to background.
Though i fixed it by changing configuration in .plist
 "Required background modes->
App downloads content from network"

This the Debug area message: 
2016-01-09 15:45:17.600  [281:27155]  ** -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] ** unhandled action -> <FBSSceneSnapshotAction: 0x155bef20> {
    handler = remote;
    info = <BSSettings: 0x155befe0> {
        (1) = 5;
    };
}

**Comment by muhku** [comment]
Added in the example project (commit 7833fd385e42851f1d3df3801961eca12d0a1888) and updated the wiki instructions: https://github.com/muhku/FreeStreamer/wiki/Using-the-player-in-your-own-project

**Comment by jahnsrud** [comment]
First of all, thank you for a great library!

I'm having similar issues. When dismissing the app, there is almost always a noticeable stream delay. The audio stops and/or sounds distorted, lasting from half a second up to 4-5 seconds.

Also, if the app is sent to the background before playback starts, it will usually not play until the app is reopened. I can however use remoteControlReceivedWithEvent to start streaming from the background. This was not the case with FreeStreamer 2.13.

It looks like it doesn't occur in the simulator, but it happens on all devices I've tested on (iOS 9.2, 64-bit)

When locking the device while streaming, I also receive a similar error message like sifulony. The stream then becomes unstable for a few seconds.

** -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] ** unhandled action -> <FBSSceneSnapshotAction: 0x14ee7cca0> {
    handler = remote;
    info = <BSSettings: 0x1500043e0> {
        (1) = 5;
    };
}

**Comment by muhku** [comment]
You could try increasing the buffer sizes if it helps. The idea with 3.x was overall to reduce latencies with the new decoder implementation. In 2.9.x we used bufferCount = 8 and bufferSize = 32768. In 3.x we have bufferCount = 16 and bufferSize = 8192.

**Comment by sifulony** [comment]
stutter went away after changing config of "FSAudioStream.mm"
       self.bufferCount    = 64; //Default 16
       self.bufferSize     = 32768 / 1;  //Default 32768 / 4;

**Comment by muhku** [comment]
Made a couple of adjustments. Do you still have problems with v3.1.3?

**Comment by jahnsrud** [comment]
Streaming seems to be more reliable now, but the issue still persists. I couldn't reproduce the stuttering on my iPhone test devices anymore, it only happened occasionally on my iPad Pro (and simulator). It's very noticeable when it happens, so I will look more into it.

Playback still can't be started when added to the background before buffering finishes. It worked before, is this an intended change or a bug?

**Comment by muhku** [comment]
Thanks for testing. I still bumped up the buffer sizes, so now we got about 3 seconds of PCM audio in the audio queue buffers. Change in v3.1.4. It seems this should be enough to avoid stutters in background / locking.

@jahnsrud: Would you create a new issue for the playback not being able to started from background? There are no intentional changes. Audio streamers logs (enable AS_DEBUG) would be really helpful to see what is going on.
