### ISSUE TITLE
FSAudioStream is playing audio, but stuck in buffering state

### ISSUE THREAD

**Issue by jahnsrud** [muhku/FreeStreamer#248]
Occasionally after streaming for a while, the state changes to kFsAudioStreamBuffering. The audio continues to play, but the state gets stuck on buffering, it doesn't revert back to kFsAudioStreamPlaying.

**Comment by muhku** [comment]
This was due to my attempt on trying to workaround not setting the PLAYING state from the decoder thread. Now this should be handled correctly.

**Comment by muhku** [comment]
Fix pushed out in 3.3.0.

**Comment by jahnsrud** [comment]
Great 👍
