### ISSUE TITLE
Streams overlapping 

### ISSUE THREAD

**Issue by corymsmith** [muhku/FreeStreamer#249]
Users have been reporting that the next song starts playing before the previous one finishes. Have you seen this before and any idea on the cause?

**Comment by corymsmith** [comment]
This was using 3.0.21 I believe. Not sure if the most recent versions have resolved this but figured you'd know best :)

**Comment by muhku** [comment]
I would suggest trying with 3.3.0; the playlist implementation has been improved. If this still occurs, though, I haven't checked what happens if a prebuffered stream fails (say server timeouts the prebuffered stream, will it try to restart which is a wrong behavior).

**Comment by muhku** [comment]
It indeed seems there was a corner case: if a prebuffered stream fails (FSAudioController has prebuffered the next stream) and the prebuffered stream failed, it was restarted regardless if another stream was playing. These two commits should ensure that a prebuffered stream stays in the failed state and doesn't start playing. A restart is attempted only when play() is explicitly called again (that is, user chooses the stream in the playlist). Pushed in 3.3.1.

**Comment by corymsmith** [comment]
Amazing thanks!
