### ISSUE TITLE
App won't resume playing song after pause after updating to latest version

### ISSUE THREAD

**Issue by corymsmith** [muhku/FreeStreamer#251]
I tested all version between what I was using and latest, works fine on 3.2.1 and the issue occurs after updating to 3.3.0. 

The only commit that would seem to be related appears to be: https://github.com/muhku/FreeStreamer/commit/6fe437bfe73b1e39f703fbc8d1c219b6c41666c9

Any ideas?

**Comment by AnasMostefaoui** [comment]
i'm facing the same issue here,  it's consume what remaining on the buffer then it's stop playing sound.
notice that OnStateChange and OnFailure are not triggred

**Comment by linyehui** [comment]
After updating to 3.4.1, i can't pause to continue the playback after i paused it，it works on 3.2.1.

**Comment by muhku** [comment]
The proposed fix is OK - pushed commit 2a621c903792a8526743714cba8d70c3eb8b0b36

It would be good to extend the unit tests to check this case also. 3.4.2 contains the fix.

**Comment by corymsmith** [comment]
@muhku Great thanks for the update!
