### ISSUE TITLE
[FSAudioController pause] doesn't resume properly

### ISSUE THREAD

**Issue by alecgorge** [muhku/FreeStreamer#252]
I can use the pause method to properly pause a stream, but when I call it again to resume playback I hear a blip of playback and then nothing happens until EoF is reached and playback starts at that point.

If I try to resume after EOF has been reached, nothing ever plays. The played item's state never changes either. It is stuck in the paused state.

**Comment by muhku** [comment]
Fixed in Issue #251

Upgrade to 3.4.2 or cherry pick 2a621c903792a8526743714cba8d70c3eb8b0b36

**Comment by alecgorge** [comment]
Thanks! This works perfectly!
