### ISSUE TITLE
Lots of implicit self retain warnings

### ISSUE THREAD

**Issue by grosch** [muhku/FreeStreamer#253]
Compiling FSXMLHttpRequest.m shows lots of implicit 'self' captures.  Can you clean that up please?

There's also one in FSAudioStream.mm

**Comment by muhku** [comment]
Which version are you using? Could you also please post a log of the errors?

**Comment by grosch** [comment]
.../FreeStreamer/Common/FSXMLHttpRequest.m:55:26: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                         _lastError = FSXMLHttpRequestError_Connection_Failed;
                         ^
                         self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:58:91: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                         NSLog(@"FSXMLHttpRequest: Request failed for URL: %@, error %@", _url, [error localizedDescription]);
                                                                                          ^
                                                                                          self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:65:30: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                             _lastError = FSXMLHttpRequestError_Invalid_Http_Status;
                             ^
                             self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:68:96: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                             NSLog(@"FSXMLHttpRequest: Unable to receive content for URL: %@", _url);
                                                                                               ^
                                                                                               self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:78:26: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                         _xmlDocument = xmlReadMemory([data bytes],
                         ^
                         self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:84:31: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                         if (!_xmlDocument) {
                              ^
                              self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:85:30: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                             _lastError = FSXMLHttpRequestError_XML_Parser_Failed;
                             ^
                             self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:88:98: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                             NSLog(@"FSXMLHttpRequest: Unable to parse the content for URL: %@", _url);
                                                                                                 ^
                                                                                                 self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:99:37: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                         xmlFreeDoc(_xmlDocument), _xmlDocument = nil;
                                    ^
                                    self->
.../FreeStreamer/Common/FSXMLHttpRequest.m:99:52: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                         xmlFreeDoc(_xmlDocument), _xmlDocument = nil;
                                                   ^
                                                   self->

**Comment by grosch** [comment]
Go to your Build Settings, and search for 'self' in the filter.  You'll see an option for "Implicit retain of 'self' within block" which is off by default.  Turn it on and you'll see all of these.

**Comment by grosch** [comment]
Sorry, forgot to specify I'm using the most recent version, downloaded just a few moments ago.

**Comment by muhku** [comment]
Fixed in v3.4.4

**Comment by grosch** [comment]
Would you update the CocoaPod please?

**Comment by grosch** [comment]
OK, I don't think this is 100% fixed.  The warnings are gone now, but you're still using 'self' in multiple places instead of strongSelf.

For example, I'm looking in FSXMLHttpRequest.m in the start function.  Have you run this through Instruments to see if you've got a retain cycle still?
