### ISSUE TITLE
Unable to determine content type

### ISSUE THREAD

**Issue by grosch** [muhku/FreeStreamer#254]
This newer version fails to start as it can't determine the content type from the URL.  I'm using an FSAudioController pointing at a ShoutCast stream, so it's an audio/mpeg stream.  Is there a way I can just tell it that?

**Comment by muhku** [comment]
Well now you can beginning from v3.4.3 :)

Supply your own configuration for FSAudioController and set requireStrictContentTypeChecking = NO

**Comment by muhku** [comment]
http://muhku.github.io/FreeStreamer/api/Classes/FSStreamConfiguration.html#//api/name/requireStrictContentTypeChecking

**Comment by grosch** [comment]
Could you please provide more details?  This is not working:

    self.audio = [[FSAudioController alloc] initWithUrl:[NSURL URLWithString:@"http://.....:8025/"]];
    self.audio.configuration = [[FSStreamConfiguration alloc] init];
    self.audio.configuration.requireStrictContentTypeChecking = NO;

**Comment by grosch** [comment]
Hi muhku, can you provide usage instructions please for when using an FSAudioController?
