### ISSUE TITLE
Make maxRetryCount public

### ISSUE THREAD

**Issue by PatrikBillgren** [muhku/FreeStreamer#258]
In our project we'd like to have the property maxRetryCount public. We'd like to set it to 0; in order to use a specific retry logic.

Do you agree with this, or should we solve this in another way?

**Comment by muhku** [comment]
Hello, if you want to make a PR this sounds like an OK change to me :)

**Comment by PatrikBillgren** [comment]
Alright, I'll do, thanks!

**Comment by PatrikBillgren** [comment]
The other properties are named "max*", though. 
For example maxPacketDescs and maxBounceCount.

**Comment by muhku** [comment]
Thanks! You are right. Let's keep maxRetryCount then.

**Comment by muhku** [comment]
Released in v3.5.3
