### ISSUE TITLE
Does FreeStreamer can run in background thread?

### ISSUE THREAD

**Issue by littlewu0** [muhku/FreeStreamer#261]
Hello, Muhku.
 
I found that FreeStreamer is running in main thread, or maybe I am wrong . I want to make sure that it can run in sub thread or not.

Thank you!

**Comment by muhku** [comment]
It does use separate threads for decoding and playback. I/O runs in the main thread as it uses non-blocking I/O. The idea is that you should place the streamer itself in the main thread and let it handle the threading. Currently there are assertions which prevent you to use any other than main thread for the streamer object.

If you know what you are doing and protect the access with mutexes, you should be fine. In that case you need to remove the main thread assertions. There's also an FAQ question which covers this a bit: https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ#is-it-safe-to-use-the-streamer-from-multiple-threads

**Comment by littlewu0** [comment]
Thank you very much for your answer.

And I found anther problem. The FreeStreamer does't handle redirect url, like 302 http code.
If I need to handle this, I think I should add this feature in "http_stream" class.

So if you have any suggestion , just tell me. 

Thank you .

**Comment by muhku** [comment]
The kCFStreamPropertyHTTPShouldAutoredirect property (see https://github.com/muhku/FreeStreamer/blob/master/FreeStreamer/FreeStreamer/http_stream.cpp#L366) should take care of this if you are using FSAudioStream.

**Comment by muhku** [comment]
Closing. This and the FAQ item should address the question.
