### ISSUE TITLE
Should I just alloc singleton "FSAudioStream" object for all audio playing?

### ISSUE THREAD

**Issue by littlewu0** [muhku/FreeStreamer#262]
When I read the "FSAudioStream" class interface, I found that it does many things in its "dealloc" function.
So should  I just alloc one singleton  "FSAudioStream" object for all audio playing?
while I found that in your demo, you alloc different "FSAudioStream" object for different audio playing.

Thank you !

**Comment by muhku** [comment]
I don't recommend using singletons. Create a stream when you need it and deallocate the object when the stream is no longer needed. By keeping the stream in a singleton instance all the time, cache cleanup will not be performed and you may waste memory. One possible pattern is to keep the stream in a view controller and then release it in viewWillDisappear or such.
