### ISSUE TITLE
Stream not changing by playFromURL

### ISSUE THREAD

**Issue by skopanev** [muhku/FreeStreamer#264]
I've found if I play by playFromURL m3u stream, then switch to another non-m3u stream then previous m3u will plays again (not switching to new one).
Simplest solution I've found in function **stop** remove all playlistItems and it works fine.

Hope @muhku will provide us with correct solution. Thanks,

**Comment by dimovskidamjan** [comment]
I've also encountered this issue. From debugging, I have found out that the FSAudioController tries to determine the content type for the second url, fails, tries to play it anyway and then ends up playing the last playlist item it successfully parsed for some reason. This was not the case in earlier versions of FreeStreamer.

**Comment by dimovskidamjan** [comment]
@muhku I suggest changing the method:
`- (FSCheckContentTypeRequest *)checkContentTypeRequest
{
    if (!_checkContentTypeRequest) {
        __weak FSAudioController *weakSelf = self;
        
        _checkContentTypeRequest = [[FSCheckContentTypeRequest alloc] init];
        _checkContentTypeRequest.url = self.url;
        _checkContentTypeRequest.onCompletion = ^() {
            if (weakSelf.checkContentTypeRequest.playlist) {
                // The URL is a playlist; retrieve the contents
                [weakSelf.parsePlaylistRequest start];
            } else if (weakSelf.checkContentTypeRequest.xml) {
                // The URL may be an RSS feed, check the contents
                [weakSelf.parseRssPodcastFeedRequest start];
            } else {
                // Not a playlist; try directly playing the URL
                weakSelf.readyToPlay = YES;
                [weakSelf play];
            }
        };
        _checkContentTypeRequest.onFailure = ^() {
            // Failed to check the format; try playing anyway
            
#if defined(DEBUG) || (TARGET_IPHONE_SIMULATOR)
            NSLog(@"FSAudioController: Failed to check the format, trying to play anyway, URL: %@", weakSelf.audioStream.url);
#endif
            [weakSelf.playlistItems removeAllObjects];
            weakSelf.readyToPlay = YES;
            [weakSelf play];
        };
    }
    return _checkContentTypeRequest;
}`

to include the `[weakSelf.playlistItems removeAllObjects];` line I have added, in order to clear any playlist leftovers.

**Comment by skopanev** [comment]
@dimovskidamjan why you think we should add removeAllObjects in checkContentTypeRequest instead of stop method? 

Thanks,

**Comment by dimovskidamjan** [comment]
@skopanev I've just found that it works good this way, I can't exactly explain why. I will try it right now with the "removeAllObjects" call in the stop method and will inform you on the results.

**Comment by dimovskidamjan** [comment]
@skopanev I've tried it your way and it also works, as far as I could see. I will submit a pull request.
