### ISSUE TITLE
dyld: Library not loaded: @rpath/FreeStreamer.framework/FreeStreamer

### ISSUE THREAD

**Issue by inix** [muhku/FreeStreamer#273]
My step:
1.clone this FreeStreamer;
2.open Xcode Project:  FreeStreamer/FreeStreamer.xcodeproj
3.set Target version: 7.0
4.build the project
5.copy,paste the FreeStreamer.framework under "Debug-iphoneos" directory to My project.

When I run project,error prompt: "dyld: Library not loaded: @rpath/FreeStreamer.framework/FreeStreamer"

Do I miss something in these step? Are my link step wrong?

**Comment by muhku** [comment]
This is fixed in the example project.
