### ISSUE TITLE
How can I delete the cache of the specified music

### ISSUE THREAD

**Issue by sdwdjzhy** [muhku/FreeStreamer#279]
RT:
I need to delete the cache of the specified music.
And  I want to show a list of music that has been cached.
But I can't find the relationship between the cache and the music.

the end, why I can not play the file which is use "outputFile" method product.

**Comment by muhku** [comment]
The cache function determines the file name based on the SHA1 sum for the stream URL. There is no reverse lookup so you would need to keep a database of the URLs and SHA1 sums.

**Comment by sdwdjzhy** [comment]
OK, Thank you! I would try.
