### ISSUE TITLE
Some Mp3's erroring out

### ISSUE THREAD

**Issue by corymsmith** [muhku/FreeStreamer#287]
Any idea why certain MP3 files streamed from a website would work and others won't? Different metadata?

**Comment by corymsmith** [comment]
The particular error is "Failed to open stream", when tracing through the code it fails out when calling .open(), could it be related to ID3 tags? The mp3's were generated using the YouTube-DL library. Some work and others don't.

**Comment by muhku** [comment]
Any trace logs?

**Comment by corymsmith** [comment]
[FSAudioController.m:505] playFromPlaylist. Adding stream proxy for 
[audio_stream.cpp:268 thread 70b] void astreamer::Audio_Stream::close(bool): enter
[audio_stream.cpp:353 thread 70b] void astreamer::Audio_Stream::close(bool): leave

Playing [FreeStreamer 3.5.7] URL: 
bufferCount: 64
bufferSize: 8192
maxPacketDescs: 512
httpConnectionBufferSize: 8192
outputSampleRate: 44100.000000
outputNumChannels: 2
bounceInterval: 10
maxBounceCount: 4
startupWatchdogPeriod: 30
maxPrebufferedByteCount: 10000000
format: formatID: , sample rate: 0.000000
bit rate: 0.000000
userAgent: FreeStreamer/3.5.7 (iOS 9.3)
cacheDirectory: /Users/corysmith/Library/Developer/CoreSimulator/Devices/DF5FE2AB-9F0C-4574-B7E8-DEF6A189B970/data/Containers/Data/Application/DF4DA8B1-B6BC-4EF3-BF97-069EB878707B/Documents
predefinedHttpHeaderValues: (null)
cacheEnabled: YES
seekingFromCacheEnabled: YES
automaticAudioSessionHandlingEnabled: NO
enableTimeAndPitchConversion: NO
requireStrictContentTypeChecking: YES
maxDiskCacheSize: 256000000
usePrebufferSizeCalculationInSeconds: YES
usePrebufferSizeCalculationInPackets: NO
requiredPrebufferSizeInSeconds: 7.000000
requiredInitialPrebufferedByteCountForContinuousStream: 256000
requiredInitialPrebufferedByteCountForNonContinuousStream: 256000
requiredInitialPrebufferedPacketCount: 32
File not cached
[audio_stream.cpp:1174 thread 70b] void astreamer::Audio_Stream::closeAndSignalError(int, CFStringRef): error 1
[audio_stream.cpp:1210 thread 70b] state set: FAILED
[audio_stream.cpp:268 thread 70b] void astreamer::Audio_Stream::close(bool): enter
[audio_stream.cpp:353 thread 70b] void astreamer::Audio_Stream::close(bool): leave

FSAudioStream: Error opening the stream: Input stream open error [FreeStreamer 3.5.7] URL: 
bufferCount: 64
bufferSize: 8192
maxPacketDescs: 512
httpConnectionBufferSize: 8192
outputSampleRate: 44100.000000
outputNumChannels: 2
bounceInterval: 10
maxBounceCount: 4
startupWatchdogPeriod: 30
maxPrebufferedByteCount: 10000000
format: formatID: , sample rate: 0.000000
bit rate: 0.000000
userAgent: FreeStreamer/3.5.7 (iOS 9.3)
cacheDirectory: /Users/corysmith/Library/Developer/CoreSimulator/Devices/DF5FE2AB-9F0C-4574-B7E8-DEF6A189B970/data/Containers/Data/Application/DF4DA8B1-B6BC-4EF3-BF97-069EB878707B/Documents
predefinedHttpHeaderValues: (null)
cacheEnabled: YES
seekingFromCacheEnabled: YES
automaticAudioSessionHandlingEnabled: NO
enableTimeAndPitchConversion: NO
requireStrictContentTypeChecking: YES
maxDiskCacheSize: 256000000
usePrebufferSizeCalculationInSeconds: YES
usePrebufferSizeCalculationInPackets: NO
requiredPrebufferSizeInSeconds: 7.000000
requiredInitialPrebufferedByteCountForContinuousStream: 256000
requiredInitialPrebufferedByteCountForNonContinuousStream: 256000
requiredInitialPrebufferedPacketCount: 32

**Comment by corymsmith** [comment]
Closing this. Looks like our API was returning empty URL's only for some tracks
