### ISSUE TITLE
Playing stops in background

### ISSUE THREAD

**Issue by skopanev** [muhku/FreeStreamer#299]
Hi @muhku,

I've found that current version stops playing in background which looks strange becase for me it is one of main feature of library.
I've found that in FSAudioController method
`- (FSAudioStream *)audioStream`
automaticAudioSessionHandlingEnabled parameter is disabled which removed all previous existing audiosession handling.
I've replaced by YES and for now it works as usual. 
`// Disable audio session handling`
 ` conf.automaticAudioSessionHandlingEnabled = YES;`

I think it should be YES by default. Thanks,

**Comment by muhku** [comment]
Thanks for spotting this. Pull request #294 broke this so if explicitly set, one can disable session handling by using the automaticAudioSessionHandlingEnabled property in FSAudioController.

**Comment by muhku** [comment]
http://muhku.github.io/FreeStreamer/api/Classes/FSAudioController.html#//api/name/automaticAudioSessionHandlingEnabled
