### ISSUE TITLE
iOS 10, [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0

### ISSUE THREAD

**Issue by seropusha** [muhku/FreeStreamer#313]
When FreeStreamer  buffering the mp3 file, I get this message in console many times (3 in 1 sec), and music play with longest interruptions. 
iOS 10 in simulator

**[aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0**

**Comment by Izzyjm** [comment]
I think it is a bug in xcode

**Comment by hashmal** [comment]
it is indeed a bug in Xcode when running on a simulator.

workaround:

- go to *Edit Scheme* > *Run* > *Arguments*
- add environment variable `OS_ACTIVITY_MODE`, value `disable`

**Comment by seropusha** [comment]
thanks guys

**Comment by mahong125** [comment]
学习了

**Comment by sazzad7002** [comment]
Thanks  working **hashmal**

**Comment by Rajaprahlad** [comment]
Thanks Hash
<img width="907" alt="screen shot 2017-08-30 at 10 53 14 am" src="https://user-images.githubusercontent.com/20362841/29887217-8de15fee-8d71-11e7-8cd8-42da4b6b66fb.png">
mal It worked

**Comment by Anthony2225** [comment]
上边的解决办法 只能不报错,但是还是不能播放a

**Comment by GowthamDeveloper** [comment]
@hashmal : Great...! Working thanks.

**Comment by qqskda** [comment]
> it is indeed a bug in Xcode when running on a simulator.
> 
> workaround:
> 
> * go to _Edit Scheme_ > _Run_ > _Arguments_
> * add environment variable `OS_ACTIVITY_MODE`, value `disable`

Thanks!
