### ISSUE TITLE
[Crash] Audio_Queue::State Audio_Queue::state()

### ISSUE THREAD

**Issue by IvanChan** [muhku/FreeStreamer#322]
![c88ad386-0104-4590-a9e5-891c9a939ca8](https://cloud.githubusercontent.com/assets/3829585/20996406/4cda6ff4-bd38-11e6-8603-ffb5b1952550.png)

**Comment by rickyjwhong** [comment]
+ 1

**Comment by muhku** [comment]
Commit f03be2e4450b3a9e8fa4bbbcefa2ec43b929bb93 introduced crashing when checking the audio queue state without mutex locking. Attempted to fix in 99e2d44634b9a4e32d1c784da6018eed762769d4 but it still crashed when accessing deallocated queue instance.

I did more look and it seems the original "fix" is just bogus. The correct way is to check the queue callback status (paused) and this is already done.

Should have checked this a lot more carefully before this kind of crap ends up in the mainline. Will be checking the upcoming PRs with a lot more detail especially if it touches the core parts.

**Comment by muhku** [comment]
Pod 3.7.2 pushed out. Let's hope it is the end of this miserable story. Let me know if still problems.

**Comment by IvanChan** [comment]
@muhku 
I test this crash for a little bit, I think the problem is decode-loop is still running after stream destroyed.

And I tried to fix this crash like below, it works for now, still need further test.

audio_stream.cpp
```
void Audio_Stream::decodeSinglePacket(CFRunLoopTimerRef timer, void *info)
{
   ..........

    if (!THIS->m_decoderShouldRun || !THIS->decoderShouldRun()) {
        pthread_mutex_lock(&THIS->m_streamStateMutex);
        THIS->m_decoderActive = false;
        pthread_mutex_unlock(&THIS->m_streamStateMutex);
        return;
    }

   .............
}
```
