### ISSUE TITLE
When I quickly switch songs will crash （3.7.1）

### ISSUE THREAD

**Issue by xiaoio4** [muhku/FreeStreamer#323]
Application received signal SIGSEGV
0 YiKa 0x00000001015d036c 0x00000000015a036c +[BMCUncaughtExceptionHandler exceptionBacktrace] + 60
1 YiKa 0x00000001015d0808 0x00000000015a0808 BugoutSignalHandler + 344
2 libsystem_platform.dylib 0x000000018e77c338 0x0000000000006338 _sigtramp + 36
3 YiKa 0x000000010055a8b8 0x000000000052a8b8 _ZN9astreamer11Audio_Queue12currentStateEv + 44
4 YiKa 0x000000010055fd90 0x000000000052fd90 _ZN9astreamer12Audio_Stream16decoderShouldRunEv + 56
5 YiKa 0x0000000100560020 0x0000000000530020 _ZN9astreamer12Audio_Stream18decodeSinglePacketEP16__CFRunLoopTimerPv + 408
6 CoreFoundation 0x000000018f6988f4 0x00000000000dd8f4 + 28
7 CoreFoundation 0x000000018f698608 0x00000000000dd608 + 872
8 CoreFoundation 0x000000018f697ec4 0x00000000000dcec4 + 244
9 CoreFoundation 0x000000018f695ac0 0x00000000000daac0 + 1572
10 CoreFoundation 0x000000018f5c4048 0x0000000000009048 CFRunLoopRunSpecific + 444
11 CoreFoundation 0x000000018f6118d4 0x00000000000568d4 CFRunLoopRun + 112
12 YiKa 0x000000010055b8c0 0x000000000052b8c0 _ZN9astreamer12Audio_Stream10decodeLoopEPv + 176
13 libsystem_pthread.dylib 0x000000018e780850 0x0000000000003850 + 240
14 libsystem_pthread.dylib 0x000000018e780760 0x0000000000003760 + 0
15 libsystem_pthread.dylib 0x000000018e77ddac 0x0000000000000dac thread_start + 4
<img width="1141" alt="2016-12-08 4 54 56" src="https://cloud.githubusercontent.com/assets/5752159/21003580/2d5bbb36-bd67-11e6-947b-3064a1c5d054.png">

**Comment by xiaoio4** [comment]
![Uploading 屏幕快照 2016-12-08 下午4.54.56.png…]()

**Comment by muhku** [comment]
See #322
