### ISSUE TITLE
Claims no internet connection with Shoutcast v2 URL

### ISSUE THREAD

**Issue by grosch** [muhku/FreeStreamer#336]
I'm successfully using your library (originally from 3.4.4 but seems to work still with update to 3.7.2) to stream s Shoutcast stream.  The client has now stated they are moving to Shoutcast v2 and gave me a new IP address and port.   

Is it possible to use your great library with a v2 Shoutcast server?  If I go to the IP/port directly via my browser I can play the stream so I know I don't have a typo there, but when I try to run it just immediately tells me there is no internet connection.

I had the same format unknown type errors with the v1 server as well.

> 2017-02-14 22:06:23.080320 Daytona's Surf[25059:13183945] FSCheckContentTypeRequest: Failed to determine content type from the URL: 199.180.75.58:9061
> 2017-02-14 22:06:23.080378 Daytona's Surf[25059:13183945] FSCheckContentTypeRequest: Unable to determine content-type for the URL: 199.180.75.58:9061, error unsupported URL
> 2017-02-14 22:06:23.082273 Daytona's Surf[25059:13183945] FSAudioController: Failed to check the format, trying to play anyway, URL: (null)
> 2017-02-14 22:06:23.097307 Daytona's Surf[25059:13183945] FSAudioStream: Error opening the stream: Input stream open error [FreeStreamer 3.4.4] URL: 199.180.75.58:9061
> bufferCount: 64
> bufferSize: 8192
> maxPacketDescs: 512
> httpConnectionBufferSize: 8192
> outputSampleRate: 48000.000000
> outputNumChannels: 2
> bounceInterval: 10
> maxBounceCount: 4
> startupWatchdogPeriod: 30
> maxPrebufferedByteCount: 10000000
> format: formatID: , sample rate: 0.000000
> bit rate: 0.000000
> userAgent: FreeStreamer/3.4.4 (iOS 10.2)
> cacheDirectory: /var/mobile/Containers/Data/Application/0AF17CA2-04DF-443F-A64D-8D90A8C94454/Documents
> predefinedHttpHeaderValues: (null)
> cacheEnabled: YES
> seekingFromCacheEnabled: YES
> automaticAudioSessionHandlingEnabled: NO
> enableTimeAndPitchConversion: NO
> requireStrictContentTypeChecking: NO
> maxDiskCacheSize: 256000000
> usePrebufferSizeCalculationInSeconds: YES
> usePrebufferSizeCalculationInPackets: NO
> requiredPrebufferSizeInSeconds: 7.000000
> requiredInitialPrebufferedByteCountForContinuousStream: 256000
> requiredInitialPrebufferedByteCountForNonContinuousStream: 256000
> requiredInitialPrebufferedPacketCount: 32
> 2017-02-14 22:06:23.097482 Daytona's Surf[25059:13183945] FSAudioStream: Internet connection not available. Not attempting a restart
>

**Comment by grosch** [comment]
Hi guys/gals, any comments here?  Client is asking me for status of upgrading.

**Comment by gabek** [comment]
Did you try http://199.180.75.58:9061/stream ?

**Comment by grosch** [comment]
@gabek Thank you!  That was exactly what I needed!
