### ISSUE TITLE
Seek after PLAYING, might cause slience

### ISSUE THREAD

**Issue by IvanChan** [muhku/FreeStreamer#341]
I try to seek after **PLAYING** come.

the audio might keep playing for a while, and become slience. no state changed callback.

**Comment by gabek** [comment]
Just for clarification, what does SDWebImageDownloader have to with FreeStreamer?

**Comment by IvanChan** [comment]
@gabek pasteboard problem, my bad

**Comment by IvanChan** [comment]
Set seekingFromCacheEnabled = NO resolve this problem

**Comment by IvanChan** [comment]
Although set seekingFromCacheEnabled = NO resolve this problem

But If I have buffered 5mins and currently lost internet, I can NOT seek!

**Comment by WeiKnowi** [comment]
I have the same problem,but set seekingFromCacheEnabled = NO, this problem still here.What should i do.

**Comment by DarthRumata** [comment]
Version: 3.7.4
Steps:

Play stream from beginning
Seek some position
Result:

no sound
Playback is running
volume 100%
AVAudioSession is active
Workaround: after seeking again sound is heard.
Reproducing with high probability if breakpoint in xcode is fired

**Comment by muhku** [comment]
Huge thanks, @DarthRumata! The fix looks good, although I did a bit of reformatting to make it easier to understand what is happening. Fix in 676e65f89036ffb82636af16bf983c29bc354531

**Comment by muhku** [comment]
Fix available in v3.8.0 release and in CocoaPods. Closing.

**Comment by bizibizi** [comment]
are you sure that it fixed? i am getting some kind of similar issue in 3.8.0. How should I set seek btw? Trying to seek within .mp3

**Comment by bizibizi** [comment]
that code does not work:
            var position = FSStreamPosition()
            position.playbackTimeInSeconds = player.currentTimePlayed.playbackTimeInSeconds - 15
            player.seek(to: position)

**Comment by GodzzZZZ** [comment]
@bizibizi did you find the way to resolve this problem?
