### ISSUE TITLE
http_stream should open proxy setting for user

### ISSUE THREAD

**Issue by IvanChan** [muhku/FreeStreamer#342]
like SDWebImageDownloader

```
- (nonnull instancetype)initWithSessionConfiguration:(nullable NSURLSessionConfiguration *)sessionConfiguration;

```

Freestream should have some kind of api like this, in order to customize download behavior, such as proxy.

**Comment by CodeEagle** [comment]
Try [`FreePlayer`](https://github.com/CodeEagle/FreePlayer) here, a swift version of `FreeStreamer`

# Digest(Tested), Basic(not tested) proxy support

> Feature
- Pure Swift implementation, no need to mixing Objective-C/C++ in project
- Friendly for Swift project

**Comment by muhku** [comment]
@CodeEagle I deleted your comment. It is a common manner in open source communities not to endorse your own projects as a solution to a problem.

By default, FreeStreamer uses the iOS proxy settings: https://github.com/muhku/FreeStreamer/blob/master/FreeStreamer/FreeStreamer/http_stream.cpp#L370

If you want to add proxy server as a property in https://muhku.github.io/FreeStreamer/api/Classes/FSStreamConfiguration.html, I can review a PR.

**Comment by CodeEagle** [comment]
Sorry for that
