### ISSUE TITLE
Excuse me.please  look here.why?

### ISSUE THREAD

**Issue by pheromone** [muhku/FreeStreamer#345]
.isPlaying() 方法怎么一直返回false,还有这个警告:Notice: FreeStreamer running on simulator, low latency audio not available!但是我仍然可以播放,有影响吗?

sPlaying () method always returns false?and this warning: Notice: FreeStreamer running on simulator, low latency audio is not available!But I can still play, influential?

**Comment by CodeEagle** [comment]
Try [`FreePlayer`](https://github.com/CodeEagle/FreePlayer) here, a swift version of `FreeStreamer`

> Feature
- Pure Swift implementation, no need to mixing Objective-C/C++ in project
- Friendly for Swift project
