### ISSUE TITLE
Seems This repo not maintenance in time

### ISSUE THREAD

**Issue by CodeEagle** [muhku/FreeStreamer#348]
I had wrote a Swift version `FreeStreamer`, call [`FreePlayer`](https://github.com/CodeEagle/FreePlayer), welcome and have a try

> Feature
- Pure Swift implementation, no need to mixing Objective-C/C++ in project
- Friendly for Swift project

**Comment by muhku** [comment]
Hi, I'm totally OK with your port but please include the original BSD license in your FreePlayer repository: https://github.com/muhku/FreeStreamer/blob/master/LICENSE.txt

Otherwise you are not complying with the BSD license and we have a problem here.

**Comment by CodeEagle** [comment]
ok

**Comment by muhku** [comment]
Thanks, repo is looking good now.
