### ISSUE TITLE
Current Progress

### ISSUE THREAD

**Issue by jogasinghbajwa** [muhku/FreeStreamer#363]
Hi, i'm new in iOS Development, I'm trying to embed your streamer class in my project. It is easy to get Stream's Duration by using existing method. But i'm still unable to get it's Current progress, could you please give me idea how can i get current progress of the stream to show it to the user.
Thanks in advance.

**Comment by commando24** [comment]
You can use stream.currentTimePlayed.playbackTimeInSeconds to get current played duration of file.
