### ISSUE TITLE
Incorrect progress after playing for a while

### ISSUE THREAD

**Issue by lvialle** [muhku/FreeStreamer#374]
Hello! 

FreeStreamer is a great piece of code and congratulations for that! Unfortunately I am facing an issue that I am trying to debug since a few days, and this one is a pain. At least I start to know the code and I see how it works :D

The issue is that after playing at least 15 minutes of a mp3 file, and wait that the end of the stream is reached, give an incorrect position when you are at the end of the stream:

`timeplayed: 1532.928101/1539.456177, m_seekoffset: 0.432620, AQSampleTime: 866.928050
[audio_stream.cpp:1715 thread 6d0b] decoder: converter run out data: bailing out
[audio_stream.cpp:803 thread 403] virtual void astreamer::Audio_Stream::audioQueueBuffersEmpty(): enter
[audio_stream.cpp:891 thread 403] 0 cached packets, enqueuing
[audio_stream.cpp:902 thread 403] virtual void astreamer::Audio_Stream::audioQueueBuffersEmpty(): closing the audio queue
[audio_stream.cpp:1289 thread 403] state set: PLAYBACK_COMPLETED
[audio_stream.cpp:270 thread 403] void astreamer::Audio_Stream::close(bool): enter
[audio_stream.cpp:1923 thread 403] Watchdog invalidated
[audio_stream.cpp:1215 thread 403] Releasing audio queue
[audio_stream.cpp:1292 thread 403] unknown state
[audio_stream.cpp:355 thread 403] void astreamer::Audio_Stream::close(bool): leave`

timeplayed provide the current progress provided by `playbackPosition.timePlayed` from `audio_stream.cpp` and the 1539 value is `durationInSeconds()`.

AQSampleTime is the value from `queueTime.mSampleTime` from the audio queue. I tested without seeking (`m_seekoffset` being at 0.0) and it doesn't help.

So the problem is that the audio cut before the end of the stream and we receive `PLAYBACK_COMPLETED`, and as you can see, the progress doesn't reach the duration. The duration is correct as I checked it against others players.

I also tried to change the `playbackPosition.timePlayed` calculation by counting the number of frames fed to the audio queue and then divide by the sample rate, and it doesn't help (just one second difference).

Any idea? You can test with this mp3: http://www.podtrac.com/pts/redirect.mp3/frenchspin.com/sites/positron/audio/positron_75.mp3
Seek to 12:00, then leave it running until the end, you will see that the end of the stream is cut by a few seconds.
If you seek to a later position, then it works better, so it's like the progress is losing it's sync with the audio queue for some reason.

**Comment by muhku** [comment]
> So the problem is that the audio cut before the end of the stream and we receive PLAYBACK_COMPLETED, and as you can see, the progress doesn't reach the duration.

Hope I understood the problem correctly.

I think you may have been focusing on the wrong place. I believe the problem here is not the current playback position - that should work correctly - but rather as you describe it, the audio cut before the end of stream. You could try changing the Audio_Stream::decoderShouldRun() loop and remove the check for state == PLAYBACK_COMPLETED. In that case the decoder should keep running regardless the stream ending. Then check if you get the correct playback position. Now if my guess is correct, this would indicate a race condition between the stream ending (PLAYBACK_COMPLETED) and the decoder getting finished. Essentially the decoder didn't have enough time to finish converting the rest of the audio packets. So that's my guess without further investigation.

**Comment by lvialle** [comment]
Many thanks for your answer. So I tested removing the check for the state about the playback completed in Audio_Stream::decoderShouldRun() and unfortunately that does not help.

What I forgot to mention is that we go thru the following:
- We get a lot of `decoder: converter run out data: bailing out` (not sure what it means)
- We enter `Audio_Stream::audioQueueBuffersEmpty()` which does not buffer since `playbackDataCount() == 0` and `m_inputStreamRunning == false` since the end of the file is supposed to be in the buffer.

Then everyting is closed because m_playPacket is NULL at the end of audioQueueBuffersEmpty().

I guess m_playPacket is the issue since it's NULL before all packets are decoded? I just don't understand why.

**Comment by muhku** [comment]
I pushed a small test in 20b58c4735addb0af0105778d704a28620f02421 - to me it looks like the file plays until 25:39, should that be the correct duration?

**Comment by lvialle** [comment]
I tested with your change, that worked two times in a row (playing the full file), then on the third attempt it again stopped before the end:
timeplayed: 1534.732788/1539.456177, m_seekoffset: 0.000000, AQSampleTime: 1534.732771

and yes 25:39 (1539 seconds) is the correct duration, verified against a lot of others players and Audacity

**Comment by muhku** [comment]
This is starting to sound strange indeed. I would recommend downloading the file locally and using the local file playback to check first if the problem also occurs without the HTTP input stream.

**Comment by lvialle** [comment]
I just ran 3 tests without HTTP, and it works fine with a bundled file (the exact same file, that I downloaded) within the project. So the issue is definitely with HTTP, we're progressing :D

**Comment by muhku** [comment]
The next step which could be tried is to place the same file to _another_ web server. If the problem doesn't reoccur with the new server, we know that there's something fishy happening when the file is transferred from the original server.

**Comment by lvialle** [comment]
I did and tested, and it works. So definitely there is an issue with the server. While I know that badly configured servers exists, I need to figure out what's wrong because I won't be able to relocate those files as they don't belong to me.

What could be the issue with the server? Contentlength being too short?

Again, I really appreciate your help on this, you helped a lot already!

**Comment by muhku** [comment]
You are welcome!

There could be multiple reasons for the server failure. I would firstly disable all local caching at FreeStreamer's side (see https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ#is-it-possible-to-cache-the-streamed-files-to-disk). Also disable "automatic recovery": https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ#i-was-streaming-a-long-podcast-and-the-playback-was-interrupted-by-a-network-error-what-happened

After these steps, are you getting to start "Connection reset by peer" errors?

Also checking the headers with a network debugger is not a bad idea...

**Comment by lvialle** [comment]
I start to think that this might not be a server issue. Caching were already disabled in my tests, I disabled the automatic recovery code as well and the issue is still there.

I also checked both servers with curl, the ContentLength are correct, they also respond perfectly to the range: bytes header, and they return the same values. I checked the content returned with md5 and both servers provide exactly the same content.

What I noticed during my tests:

With a content length 24757495, m_seekoffset: 0.422877, this give a start pos of:
24757495*0.422877 = 10469375,213115
Then after leaving the player running until the end, the last HTTP read total is: 14003541
10469375,213115 + 14003541 = 24472916,213115
24472916,213115 - 24757495 (contentLength) = 284 578

That means 284Kb were missing?

On the server where I have no issues, only 64Kb were missing.

Another test (after seeking on both servers):
Server where it fails:
ContentLength: 13255705
Total bytes read: 13142222

Server where it works:
ContentLength: 13287469
Total bytes read: 13287469

So for reasons I do not understand, the HTTP code does not read until the end. However on both server, we get `kCFStreamEventEndEncountered`, but for one we seems to be getting it too soon.

**Comment by lvialle** [comment]
More weirdness, it seems that we are in the `CFReadStreamHasBytesAvailable` while loop but `CFReadStreamRead` return 0 bytes before we got all the data (and probably why we get the `kCFStreamEventEndEncountered` afterward)

Bytes read are still below the content length

**Comment by CodeEagle** [comment]
Oh, I remember this. You need to add an handler at `endEncountered`,
calculate open `position.start + bytesRead`, save `contentLength` only `status code == 200`, not override it in `status code ==206`, compare  `contentLength ` and  `position.start + bytesRead`, if not stream enough, reopen at position

**Comment by lvialle** [comment]
Well I have been thinking about checking for `kCFStreamEventEndEncountered` and then compare the contentLength and bytesRead, then reopening but that does not seem very clean to me. And I am curious to know why `CFReadStreamRead` detect the end of the stream before it's really finished.
However this could be a workaround, I agree

**Comment by CodeEagle** [comment]
Try This [MrLittleWhite/FreeStreamer/http_stream.cpp](https://github.com/MrLittleWhite/FreeStreamer/blob/master/FreeStreamer/FreeStreamer/http_stream.cpp)

**Comment by muhku** [comment]
Thanks for debugging this! Sounds definitely like a bug. If you come up with a patch proposal, I can take a look.

**Comment by lvialle** [comment]
There: https://github.com/muhku/FreeStreamer/pull/375

**Comment by muhku** [comment]
Thanks a million! Code looks clean & good fix so merged. Unfortunately a compiler warning for debug logging slipped in so I had to skip one version and v3.7.6 release is pushed to CocoaPods.
