### ISSUE TITLE
Occur no voice after seeking

### ISSUE THREAD

**Issue by littlewu0** [muhku/FreeStreamer#391]
Hello, muhku

I meet a problem. Sometimes after I seek FreeStreamer, it continue play, but no voice. And the progress continue go on.
I am sure my device has volume.

**Comment by lefex** [comment]
I meet this too.

**Comment by muhku** [comment]
Which version are you running? 676e65f89036ffb82636af16bf983c29bc354531 had fixed a similar issue.

**Comment by muhku** [comment]
Marking this as a duplicate for Issue #341
