### ISSUE TITLE
[Crash] astreamer::Audio_Stream::close(bool)

### ISSUE THREAD

**Issue by satishVekariya** [muhku/FreeStreamer#425]
> 0  FreeStreamer                   0x1018d90e4 astreamer::Audio_Stream::close(bool) (audio_stream.cpp:354)

```
 353   while (cur) {
 354       queued_packet_t *tmp = cur->next;
 355       free(cur);
 356       cur = tmp;
 357   }
```

> 1  FreeStreamer                   0x1018e50bc -[FSAudioStreamPrivate stop] (FSAudioStream.mm:1045)

```
1041   - (void)stop
1042   {
1043      _audioStream->close(true);
1044    
1045      [self endBackgroundTask];
1046   
1047      [_reachability stopNotifier];
1048      _reachability = nil;
1049   }
```

**Comment by danialmoghaddam** [comment]
Probably related to #423

**Comment by muhku** [comment]
Please check if still happens with 4.0.0, issue #423 fixed.
