### ISSUE TITLE
xcode 15 release archive error

### ISSUE THREAD

**Issue by cjnwan** [muhku/FreeStreamer#479]
xcode 15 release archive error:

http_stream.o)944: error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'APPLE_1_1500.0.40.1_0' Reader: 'LLVM APPLE_1_1500.0.40.1_0')

**Comment by lzp-coder** [comment]
请问解决了吗

**Comment by cjnwan** [comment]
> 请问解决了吗

没，你解决了吗

**Comment by coderyi** [comment]
把 LLVM_LTO 设置为NO可以解决

**Comment by cjnwan** [comment]
> LLVM_LTO

你可以吗，改成 NO 还是不行啊

**Comment by cjnwan** [comment]
> 把 LLVM_LTO 设置为NO可以解决

已解决，感谢
