### ISSUE TITLE
Implement Artwork fetching

### ISSUE THREAD

**Issue by iPonyRadio** [muhku/FreeStreamer#86]
Some (but not all) Ice/Shoutcast streams provide album artwork or station logos in their stream metadata.

Depending on the stream type, either the icy-metadata or ID3 v2 tags can contain the media.

**Comment by muhku** [comment]
Basic support for ID3v2 tag cover art added in commit 5349a316ed16ab4bb109ab8928c18f404f851aca

For ShoutCast metadata, parsing the image URLs etc. should be done at the client implementation.
