### ISSUE TITLE
EXC_BAD_ACCESS occurred in Audio_Stream:close()

### ISSUE THREAD

**Issue by Tenet1Ai** [muhku/FreeStreamer#90]
Try to play multiple mp3 files one after another:
http://slb2.anyradio.cn/10.144.14.33/anyradio-album/606/wenjian/606131.mp3
http://slb2.anyradio.cn/10.144.14.33/anyradio-album/606/wenjian/606130.mp3
http://slb2.anyradio.cn/10.144.14.33/anyradio-album/606/wenjian/606128.mp3
... ...

EXC_BAD_ACCESS occurred in Audio_Stream:close()
https://github.com/muhku/FreeStreamer/blob/master/astreamer/audio_stream.cpp#L235

![screen shot 2014-08-29 at 12 47 20 pm](https://cloud.githubusercontent.com/assets/1615950/4086497/98210054-2f37-11e4-8aff-192f4b8207fd.png)

/*
         \* Free any remaining queud packets for encoding.
         */
        queued_packet_t *cur = m_queuedHead;
        while (cur) {
            queued_packet_t *tmp = cur->next;
            free(cur);
            cur = tmp;
        }
        m_queuedHead = m_queuedTail = NULL;
        m_cachedDataSize = 0;

**Comment by hearther** [comment]
Hi, 

I found something interesting about this situation.
![audio_stream_cpp](https://cloud.githubusercontent.com/assets/5311606/5998640/9ac45d6c-ab04-11e4-8c82-929544640b66.png)

![audio_stream_cpp](https://cloud.githubusercontent.com/assets/5311606/5998663/d7fa9408-ab04-11e4-85b7-5cda1293df19.png)

I will try to reproduce it again.

**Comment by hearther** [comment]
Hi, all
I had added some code for tracing and here one result of my experiments.

2015-02-03 15:14:24:121 Player[main] V PlaybackEngine:407 start playing SOMEWHERE 
2015-02-03 15:14:24:214 Player[main] I PlaybackEngine:153 Buffering...
<<<< receive and malloc memory >>>>
streamDataCallback alloc 0x1807c170 in thread id: 807  <=== memory alloc for m_playPacket
<<<< receive and malloc memory >>>>
streamDataCallback alloc 0x180c4640 in thread id: 807  <=== memory alloc for m_queuedHead
<<<< receive and malloc memory >>>>

m_playPacket is 0x1807c170 in thread id: 807   <=== set as m_playPacket
<<<< receive and malloc memory and cache overflow>>>>
Cache overflow, disabling the HTTP stream
start cleanupCachedData
cleanupCachedData free 0x1807c170 in thread id: 807 datasize 418  <=== memory free m_playPacket
cleanupCachedData free 0x1807c330 in thread id: 807 datasize 418 
cleanupCachedData free 0x1807c4f0 in thread id: 807 datasize 418 
cleanupCachedData free 0x1815ec80 in thread id: 807 datasize 418 
cleanupCachedData free 0x1815ee40 in thread id: 807 datasize 418 
cleanupCachedData free 0x1815f000 in thread id: 807 datasize 418 
cleanupCachedData free 0x1807c6b0 in thread id: 807 datasize 418 
cleanupCachedData free 0x1807c870 in thread id: 807 datasize 418 
cleanupCachedData free 0x1807ca30 in thread id: 807 datasize 418 
cleanupCachedData free 0x1815f1c0 in thread id: 807 datasize 418 
cleanupCachedData free 0x1815f380 in thread id: 807 datasize 418 
cleanupCachedData free 0x1807cbf0 in thread id: 807 datasize 418 
cleanupCachedData free 0x1815f540 in thread id: 807 datasize 418 
cleanupCachedData free 0x1807f220 in thread id: 807 datasize 418  <=== crash cur
<<<< free lot memory >>>>

Found the last packet 0x18167dc0 to be cleaned up
cleanupCachedData free 0x18167dc0 in thread id: 807 datasize 418 
cleanupCachedData m_queuedHead 0x180c4640 m_playPacket 0x1807c170 <=== end of cleaning
Cache underflow, enabling the HTTP stream
<<<< receive and malloc memory and crash happen>>>>

(lldb) po m_playPacket
0x1807c170  <=== m_playPacket when crash happening
(lldb) po m_playPacket->next->next->next->next->next->next->next->next->next->next->next->next->next
0x1807f220    <=== cur when crash happening in playbackDataCount

And I tried to add some code, so far it didn't crash any more.
I will keep doing experiments.
https://github.com/hearther/FreeStreamer/blob/master/astreamer/audio_stream.cpp

**Comment by muhku** [comment]
@hearther: Picked your change in commit 4cb3531ae04570c71035fde9ca9508e2869e6fb1. Thanks for tracing this problem.
